this forceAddUniform "MNP_CombatUniform_DS_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_Clacker";
this addItemToUniform "ACE_IR_Strobe_Item";
this addVest "CUP_V_B_RRV_DA1";
for "_i" from 1 to 2 do {this addItemToVest "CUP_17Rnd_9x19_glock17";};
for "_i" from 1 to 5 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_MDim";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "UGL_FlareGreen_F";};
for "_i" from 1 to 2 do {this addItemToBackpack "UGL_FlareRed_F";};
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
this addHeadgear "CUP_H_USArmy_Helmet_ECH1_Sand";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "hlc_muzzle_snds_AUG";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "CUP_hgun_Glock17_blk";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "ACE_NVG_Wide";

