this forceAddUniform "MNP_CombatUniform_ROK_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "CUP_18Rnd_9x19_Phantom";};
this addVest "MNP_Vest_ROK_1";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "100Rnd_580x42_Mag_F";};
this addBackpack "MNP_B_ROK_AP";
for "_i" from 1 to 2 do {this addItemToBackpack "100Rnd_580x42_Mag_Tracer_F";};
this addHeadgear "MNP_Helmet_ROK";
this addGoggles "G_Balaclava_blk";
this addWeapon "arifle_CTARS_blk_F";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "CUP_optic_MRad";
this addWeapon "CUP_hgun_Phantom";
this addHandgunItem "CUP_acc_CZ_M3X";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
