this forceAddUniform "MNP_CombatUniform_ROK_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "hlc_30rnd_556x45_b_HK33";};
this addVest "MNP_Vest_ROK_1";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30rnd_556x45_b_HK33";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_30rnd_556x45_t_HK33";};
this addItemToVest "CUP_HandGrenade_RGD5";
this addHeadgear "H_PilotHelmetHeli_B";
this addWeapon "hlc_rifle_hk53RAS";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "CUP_optic_MRad";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
