this forceAddUniform "MNP_CombatUniform_ROK_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "CUP_18Rnd_9x19_Phantom";};
this addVest "MNP_Vest_ROK_1";
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_65x39_caseless_green_mag_Tracer";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addHeadgear "MNP_Helmet_ROK";
this addGoggles "G_Balaclava_blk";
this addWeapon "arifle_Katiba_C_F";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "CUP_optic_MRad";
this addWeapon "CUP_hgun_Phantom";
this addHandgunItem "CUP_acc_CZ_M3X";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
