this forceAddUniform "MNP_CombatUniform_ROK_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "CUP_18Rnd_9x19_Phantom";};
this addVest "MNP_Vest_ROK_1";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_65x39_caseless_green_mag_Tracer";};
this addBackpack "MNP_B_ROK_AP";
for "_i" from 1 to 6 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
this addHeadgear "MNP_Helmet_ROK";
this addGoggles "G_Bandanna_oli";
this addWeapon "arifle_Katiba_GL_F";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "CUP_optic_MRad";
this addWeapon "CUP_hgun_Phantom";
this addHandgunItem "CUP_acc_CZ_M3X";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
