this forceAddUniform "usm_bdu_w_m";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "MNP_Vest_USMC";
for "_i" from 1 to 4 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 10 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addBackpack "B_Carryall_khk";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 6 do {this addItemToVest "SmokeShell";};
this addHeadgear "usm_helmet_pasgt_w_m";
this addGoggles "G_Bandanna_shades";
this addWeapon "hlc_rifle_CQBR";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "CUP_hgun_Glock17_tan";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
