this forceAddUniform "usm_bdu_w_m";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "MNP_Vest_USMC";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 10 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addBackpack "B_Carryall_khk";
this addHeadgear "usm_helmet_pasgt_w_m";
this addGoggles "G_Combat";
this addWeapon "hlc_rifle_Colt727";
this addWeapon "CUP_hgun_Glock17_tan";
this linkItem "ItemMap";
this linkItem "ItemGPS";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
