this forceAddUniform "U_O_T_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShellGreen";};
this addVest "V_HarnessO_ghex_F";
for "_i" from 1 to 5 do {this addItemToVest "30rnd_580x42_Mag_F";};
for "_i" from 1 to 4 do {this addItemToVest "30rnd_580x42_Mag_Tracer_F";};
this addBackpack "B_ViperHarness_ghex_F";
for "_i" from 1 to 5 do {this addItemToBackpack "1rnd_HE_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "UGL_FlareRed_F";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "H_HelmetLeaderO_ghex_F";
this addWeapon "arifle_CTAR_GL_ghex_F";
this addPrimaryWeaponItem "optic_holosight_khk_f";
this addWeapon "RangeFinder";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "O_NVGoggles_ghex_F";
