this forceAddUniform "U_O_T_Soldier_F";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_CableTie";
this addVest "V_HarnessOGL_ghex_F";
for "_i" from 1 to 6 do {this addItemToVest "30rnd_580x42_Mag_F";};
this addItemToVest "SmokeShellGreen";
this addItemToVest "SmokeShellRed";
this addItemToVest "SmokeShell";
this addItemToVest "16rnd_9x21_green_Mag";
this addBackpack "B_FieldPack_ghex_F";
this addHeadgear "H_HelmetCrew_O_ghex_F";
this addWeapon "arifle_CTAR_ghex_F";
this addPrimaryWeaponItem "optic_holosight_khk_f";
this addWeapon "hgun_Rook40_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "O_NVGoggles_ghex_F";
