this forceAddUniform "MNP_CombatUniform_RU_Med";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_RU_T2";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_8Rnd_9x18_Makarov_M";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_VOG25_AK";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_GRD_Red";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_GRD_green";};
this addHeadgear "MNP_Helmet_RU_LT";
this addGoggles "G_Bandanna_oli";
this addWeapon "CUP_arifle_AK74M_GL";
this addWeapon "CUP_hgun_Makarov";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";