this forceAddUniform "skn_u_nbc_opf_yellow";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30Rnd_556x45_EPR_sg550";};
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 10 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 10 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "H_PASGT_basic_black_F";
this addGoggles "skn_m50_gas_mask_hood_wd";
this addWeapon "hlc_rifle_SG551SB_TAC_GL";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Top_Flashlight_Black_L";
this addPrimaryWeaponItem "CUP_optic_CompM2_low";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";
