this forceAddUniform "skn_u_nbc_opf_yellow";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30Rnd_556x45_EPR_sg550";};
this addBackpack "B_AssaultPack_blk";
this addHeadgear "H_PASGT_basic_black_F";
this addGoggles "skn_m50_gas_mask_hood_wd";
this addWeapon "hlc_rifle_SG553SB_TAC";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Top_Flashlight_Black_L";
this addPrimaryWeaponItem "CUP_optic_CompM2_low";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";
