this forceAddUniform "U_O_T_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_CableTie";
this addVest "V_HarnessO_ghex_F";
this addItemToVest "16rnd_9x21_green_Mag";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addBackpack "B_FieldPack_ghex_F";
for "_i" from 1 to 8 do {this addItemToBackpack "hlc_60rnd_545x39_t_rpk";};
this addHeadgear "H_HelmetO_ghex_F";
this addWeapon "hlc_rifle_RPK12";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addWeapon "hgun_Rook40_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "O_NVGoggles_ghex_F";
