this forceAddUniform "U_O_T_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_CableTie";
this addVest "V_HarnessO_ghex_F";
for "_i" from 1 to 6 do {this addItemToVest "30rnd_762x39_Mag_Tracer_F";};
for "_i" from 1 to 3 do {this addItemToVest "SmokeShell";};
this addItemToVest "16rnd_9x21_green_Mag";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addBackpack "B_FieldPack_ghex_F";
for "_i" from 1 to 50 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addItemToBackpack "SmokeShellGreen";
this addItemToBackpack "SmokeShellPurple";
this addItemToBackpack "SmokeShellRed";
this addHeadgear "H_HelmetO_ghex_F";
this addWeapon "arifle_AK12_F";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addWeapon "hgun_Rook40_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "O_NVGoggles_ghex_F";
