this forceAddUniform "U_O_T_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_CableTie";
this addVest "V_HarnessO_ghex_F";
for "_i" from 1 to 3 do {this addItemToVest "30rnd_762x39_Mag_Tracer_F";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "16rnd_9x21_green_Mag";
this addBackpack "B_Carryall_ghex_F";
for "_i" from 1 to 6 do {this addItemToBackpack "30rnd_762x39_Mag_Tracer_F";};
for "_i" from 1 to 3 do {this addItemToBackpack "Titan_AT";};
this addItemToBackpack "Titan_AT";
this addItemToBackpack "Titan_AP";
this addHeadgear "H_HelmetO_ghex_F";
this addWeapon "arifle_AK12_F";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addWeapon "launch_O_Titan_short_ghex_F";
this addWeapon "hgun_Rook40_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "O_NVGoggles_ghex_F";
