this forceAddUniform "U_O_T_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_MapTools";
this addVest "V_HarnessOGL_ghex_F";
for "_i" from 1 to 4 do {this addItemToVest "30rnd_762x39_Mag_Tracer_F";};
for "_i" from 1 to 3 do {this addItemToVest "1rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "16rnd_9x21_green_Mag";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addBackpack "B_FieldPack_ghex_F";
for "_i" from 1 to 6 do {this addItemToBackpack "30rnd_762x39_Mag_Tracer_F";};
for "_i" from 1 to 3 do {this addItemToBackpack "1rnd_HE_Grenade_shell";};
this addHeadgear "H_HelmetLeaderO_ghex_F";
this addWeapon "arifle_AK12_GL_F";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addWeapon "hgun_Rook40_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "O_NVGoggles_ghex_F";
