this forceAddUniform "U_O_T_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "HandGrenade";};
this addVest "V_HarnessOGL_ghex_F";
for "_i" from 1 to 6 do {this addItemToVest "30rnd_762x39_Mag_Tracer_F";};
for "_i" from 1 to 3 do {this addItemToVest "30rnd_762x39_Mag_F";};
this addHeadgear "H_HelmetO_ghex_F";
this addWeapon "arifle_AK12_F";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "O_NVGoggles_ghex_F";
