this forceAddUniform "MNP_CombatUniform_RU_Med_DB";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 3 do {this addItemToUniform "16Rnd_9x21_Mag";};
this addVest "MNP_Vest_RU_D2";
for "_i" from 1 to 9 do {this addItemToVest "hlc_30Rnd_545x39_EP_ak";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGO";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addHeadgear "MNP_Helmet_PAGST_RD";
this addWeapon "hlc_rifle_ak12";
this addPrimaryWeaponItem "optic_Yorris";
this addWeapon "hgun_Rook40_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
