this forceAddUniform "MNP_CombatUniform_RU_Med_DB";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
this addVest "CUP_V_I_RACS_Carrier_Rig_3";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGO";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_545x39_EP_ak";};
this addBackpack "CUP_B_AlicePack_Khaki";
this addItemToBackpack "ToolKit";
this addHeadgear "CUP_H_CZ_Helmet05";
this addWeapon "hlc_rifle_aku12";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
