this forceAddUniform "CUP_U_B_BAF_DDPM_UBACSLONGKNEE";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_DefusalKit";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_HiRed";};
this addVest "CUP_V_B_BAF_DDPM_Osprey_Mk3_Officer";
this addItemToVest "ACE_EntrenchingTool";
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_556x45_Stanag_L85_Tracer_Red";};
for "_i" from 1 to 8 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_FlareRed_M203";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addBackpack "CUP_B_Predator_Radio_MTP";
this addHeadgear "CUP_H_BAF_DDPM_Mk6_EMPTY";
this addWeapon "CUP_arifle_L85A2_GL";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Flashlight_Black_L";
this addPrimaryWeaponItem "optic_Holosight_smg_blk_F";
this addWeapon "ACE_VMH3";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "CUP_NVG_PVS14";
