this forceAddUniform "MNP_CombatUniform_US6co_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToUniform "hlc_12Rnd_357SIG_B_P226";};
this addVest "MNP_Vest_6co_A";
for "_i" from 1 to 7 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_M";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "CUP_B_USPack_Coyote";
this addHeadgear "MNP_Helmet_6Co";
this addWeapon "RH_M16A2";
this addWeapon "hlc_pistol_P226R_357Combat";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";