this forceAddUniform "V_ARCunis_ARCTech_bduAOR2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_MX991";
this addItemToUniform "ACE_RangeTable_82mm";
this addItemToUniform "ACE_MapTools";
this addVest "Avest1";
this addItemToVest "HandGrenade";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_30rnd_556x45_M";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "hlc_15Rnd_9x19_JHP_P226";
this addBackpack "B_Mortar_01_weapon_F";
this addHeadgear "AOR2Helm1";
this addWeapon "hlc_rifle_ACR_SBR_black";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P226R";
this addHandgunItem "hlc_acc_TLR1";
this addHandgunItem "HLC_optic_Siglite";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen6";