this forceAddUniform "MNP_CombatUniform_RU_Med_D";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "16Rnd_9x21_Mag";
this addVest "MNP_Vest_RU_D";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M";};
this addBackpack "MNP_B_RU1_CA";
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M";};
this addHeadgear "MNP_Helmet_RU_LD";
this addGoggles "G_Bandanna_blk";
this addWeapon "CUP_lmg_Pecheneg";
this addWeapon "CUP_hgun_Duty";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
