this forceAddUniform "U_B_CTRG_Soldier_F";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_CableTie";
this addVest "V_PlateCarrierIAGL_oli";
for "_i" from 1 to 3 do {this addItemToVest "SmokeShell";};
this addBackpack "B_Carryall_khk";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Yellow_M";};
this addHeadgear "SP_SSh68Helmet_Green2";
this addWeapon "CUP_lmg_PKM";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";