this forceAddUniform "CFP_CHZ_Berezka4";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_RGO";};
this addVest "SP_Tactical1_White";
for "_i" from 1 to 4 do {this addItemToVest "CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M";};
this addBackpack "CUP_B_RUS_Backpack";
for "_i" from 1 to 7 do {this addItemToBackpack "CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M";};
this addHeadgear "CUP_H_RUS_6B27";
this addWeapon "hlc_rifle_rpk74n";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";