this forceAddUniform "CFP_CHZ_Berezka4";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToUniform "CUP_HandGrenade_RGO";};
this addVest "SP_Tactical1_White";
for "_i" from 1 to 6 do {this addItemToVest "CUP_30Rnd_545x39_AK74M_M";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_30Rnd_TE1_Green_Tracer_545x39_AK74M_M";};
this addBackpack "CUP_B_RUS_Backpack";
for "_i" from 1 to 50 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 6 do {this addItemToBackpack "ACE_personalAidKit";};
this addWeapon "CUP_arifle_AK74_Early";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
