this forceAddUniform "CUP_U_C_Policeman_01";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_epinephrine";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_C_Police_Holster";
for "_i" from 1 to 8 do {this addItemToVest "CUP_8Rnd_B_Beneli_74Slug";};
for "_i" from 1 to 10 do {this addItemToVest "CUP_8Rnd_B_Beneli_74Pellets";};
this addBackpack "B_LegStrapBag_black_F";
// for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
this addItemToBackpack "ACE_personalAidKit";
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
this addHeadgear "CUP_H_C_Policecap_01";
this addWeapon "CUP_sgun_M1014";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
