this forceAddUniform "MNP_CombatUniform_Germany_S";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_BandollierB_rgr";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30Rnd_9x19_B_MP5";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addHeadgear "MNP_Helmet_Germany";
this addWeapon "hlc_smg_MP5N";
this addWeapon "CUP_hgun_Glock17_blk";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";