this AddUniform "CFP_75th_CRYE_V3_Full";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_Eagle_SPC_GL";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 6 do {this addItemToVest "hlc_20rnd_762x51_T_G3";};
this addBackpack "B_Kitbag_cbr";
for "_i" from 1 to 6 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "UGL_FlareGreen_F";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_M203";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_1Rnd_Smoke_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_20rnd_762x51_b_G3";};
this addItemToBackpack "hlc_20rnd_762x51_T_G3";
this addHeadgear "H_HelmetB_sand";
this addWeapon "HLC_Rifle_g3ka4_GL";
this addWeapon "Binocular";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this linkItem "ItemWatch";
this linkItem "ItemMap";
this linkItem "ItemGPS";

