this AddUniform "CFP_75th_CRYE_V3_Full";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_Eagle_SPC_Rifleman";
for "_i" from 1 to 6 do {this addItemToVest "hlc_20rnd_762x51_T_G3";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "CUP_7Rnd_45ACP_1911";
this addBackpack "CUP_B_AssaultPack_Coyote";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_20rnd_762x51_b_G3";};
this addHeadgear "H_HelmetB_sand";
this addWeapon "hlc_rifle_g3ka4";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "CUP_hgun_Colt1911";
this linkItem "ItemWatch";
this linkItem "ItemMap";
this linkItem "ItemGPS";

