comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

this forceAddUniform "CFP_CHZ_Berezka2";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "CFP_Tactical1_Berez";
this addItemToVest "CUP_100Rnd_556x45_BetaCMag";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_M84";};
this addBackpack "CFP_AssaultPack_White";
this addItemToBackpack "ACE_EntrenchingTool";
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_100Rnd_556x45_BetaCMag";};
this addHeadgear "CFP_OPS2017_Helmet_White";
this addGoggles "SP_Balaclava_White";
this addWeapon "CUP_arifle_MG36";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this linkItem "ItemMap";
this linkItem "ItemGPS";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
