this forceAddUniform "U_B_CombatUniform_mcam";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "11Rnd_45ACP_Mag";
this addItemToUniform "ACE_Fortify";
this addVest "V_PlateCarrier2_rgr";
for "_i" from 1 to 10 do {this addItemToVest "30Rnd_65x39_caseless_mag";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 2 do {this addItemToBackpack "200Rnd_65x39_cased_Box";};
this addHeadgear "H_HelmetB_light_snakeskin";
this addGoggles "G_Lowprofile";
this addWeapon "arifle_MX_F";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "hgun_Pistol_heavy_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
