this forceAddUniform "U_B_CombatUniform_mcam";
this addItemToUniform "11Rnd_45ACP_Mag";
this addItemToUniform "ACE_Fortify";
this addVest "V_PlateCarrier2_rgr";
for "_i" from 1 to 10 do {this addItemToVest "30Rnd_65x39_caseless_mag";};
for "_i" from 1 to 6 do {this addItemToVest "SmokeShell";};
this addBackpack "B_Carryall_cbr";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_HelmetB_light_snakeskin";
this addGoggles "G_Lowprofile";
this addWeapon "arifle_MXC_F";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "hgun_Pistol_heavy_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
