this forceAddUniform "V_ARCunis_ARCTech_bdu";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_MX991";
this addVest "custom_vest1";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 6 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_M";};
this addBackpack "AORN_Assault_Pack";
for "_i" from 1 to 4 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
this addItemToBackpack "hlc_15Rnd_9x19_JHP_P226";
this addItemToBackpack "ToolKit";
this addHeadgear "H_HelmetCrew_B";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P226R";
this addHandgunItem "hlc_acc_TLR1";
this addHandgunItem "HLC_optic_Siglite";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen6";