this forceAddUniform "U_I_CombatUniform_shortsleeve";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "9Rnd_45ACP_Mag";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_Chemlight_HiRed";};
this addVest "V_PlateCarrierIA2_dgtl";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "200Rnd_65x39_cased_Box";
this addBackpack "B_AssaultPack_dgtl";
this addItemToBackpack "200Rnd_65x39_cased_Box_Tracer";
this addItemToBackpack "200Rnd_65x39_cased_Box";
this addHeadgear "H_HelmetIA";
this addGoggles "CUP_FR_NeckScarf2";
this addWeapon "LMG_Mk200_F";
this addPrimaryWeaponItem "optic_Aco";
this addPrimaryWeaponItem "ACE_muzzle_mzls_H";
this addPrimaryWeaponItem "bipod_03_F_blk";
this addPrimaryWeaponItem "acc_pointer_IR";
this addWeapon "hgun_ACPC2_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";
