this forceAddUniform "U_I_CombatUniform_shortsleeve";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "9Rnd_45ACP_Mag";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_Chemlight_HiRed";};
this addVest "V_PlateCarrierIAGL_dgtl";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Yellow";};
this addBackpack "B_AssaultPack_dgtl";
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";
this addItemToBackpack "1Rnd_Smoke_Grenade_shell";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 5 do {this addItemToBackpack "UGL_FlareRed_F";};
for "_i" from 1 to 5 do {this addItemToBackpack "UGL_FlareYellow_F";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_HandFlare_Green";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_HandFlare_Red";};
this addItemToBackpack "150Rnd_93x64_Mag";
this addHeadgear "H_HelmetIA";
this addWeapon "arifle_Mk20_GL_F";
this addPrimaryWeaponItem "optic_ACO_grn";
this addPrimaryWeaponItem "acc_pointer_IR";
this addWeapon "hgun_ACPC2_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";
