this forceAddUniform "CUP_U_B_USArmy_Base";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "HandGrenade";};
this addVest "V_PlateCarrier1_blk";
for "_i" from 1 to 3 do {this addItemToVest "hlc_200rnd_556x45_Mdim_SAW";};
this addHeadgear "H_HelmetB_light_black";
this addWeapon "hlc_m249_pip3";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_gen8";
