this forceAddUniform "CUP_U_B_USArmy_TwoKnee";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "HandGrenade";};
this addVest "V_PlateCarrier2_blk";
for "_i" from 1 to 8 do {this addItemToVest "30rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 5 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_SmokePurple_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToVest "UGL_FlareGreen_F";};
for "_i" from 1 to 5 do {this addItemToVest "1Rnd_Smoke_Grenade_shell";};
this addItemToVest "hlc_15Rnd_9x19_B_P226";
this addHeadgear "H_HelmetB_light_black";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addWeapon "hlc_pistol_MK25TR";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_gen8";

