this forceAddUniform "CUP_U_B_USArmy_Base";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "HandGrenade";};
this addVest "V_PlateCarrier1_blk";
for "_i" from 1 to 10 do {this addItemToVest "30rnd_556x45_Stanag_Tracer_Red";};
this addHeadgear "H_HelmetB_light_black";
this addWeapon "hlc_rifle_M4";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addWeapon "CUP_launch_M136";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_gen8";
