this forceAddUniform "MNP_CombatUniform_RU_Med";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_RU_T2";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 2 do {this addItemToUniform "16Rnd_9x21_Mag";};
this addItemToVest "CUP_HandGrenade_RGD5";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "MNP_B_RU2_FP";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_GP25_M";};
this addHeadgear "MNP_Helmet_PAGST_RT";
this addGoggles "G_Bandanna_oli";
this addWeapon "hlc_rifle_ak74m_gl";
this addWeapon "hgun_Rook40_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this addItemToUniform "ACE_Fortify";