this forceAddUniform "CUP_O_TKI_Khet_Partug_03";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_OI_TKI_Jacket3_02";
for "_i" from 1 to 10 do {this addItemToVest "CUP_10x_303_M";};
this addItemToVest "CUP_6Rnd_45ACP_M";
this addBackpack "B_FieldPack_cbr";
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_ShemagOpen_khk";
this addWeapon "CUP_srifle_LeeEnfield_rail";
this addPrimaryWeaponItem "CUP_optic_MicroT1_low";
this addWeapon "CUP_hgun_TaurusTracker455";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
