comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this forceAddUniform "CUP_U_B_USMC_FROG4_WMARPAT";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "SmokeShell";
this addItemToUniform "HandGrenade";
this addVest "CUP_V_B_Eagle_SPC_AR";
for "_i" from 1 to 2 do {this addItemToVest "ACE_tourniquet";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_10Rnd_40SW_B_P229";};
for "_i" from 1 to 8 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 4 do {this addItemToBackpack "200Rnd_556x45_Box_Red_F";};
this addHeadgear "CUP_H_USMC_MICH2000_WDL";
this addGoggles "G_Aviator";
this addWeapon "hlc_rifle_416D165";
this addWeapon "hlc_pistol_P229R_40Enox";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
