this forceAddUniform "CUP_U_B_USMC_FROG4_WMARPAT";
for "_i" from 1 to 2 do {this addItemToUniform "hlc_10Rnd_40SW_B_P229";};
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "SmokeShell";
this addItemToUniform "HandGrenade";
this addVest "CUP_V_B_Eagle_SPC_AR";
for "_i" from 1 to 2 do {this addItemToVest "ACE_tourniquet";};
this addItemToVest "hlc_200rnd_556x45_M_SAW";
this addItemToVest "200Rnd_556x45_Box_Red_F";
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 3 do {this addItemToBackpack "200Rnd_556x45_Box_Red_F";};
this addHeadgear "CUP_H_USMC_MICH2000_WDL";
this addGoggles "G_Aviator";
this addWeapon "hlc_m249_pip4";
this addPrimaryWeaponItem "HLC_bipod_UTGShooters";
this addWeapon "hlc_pistol_P229R_40Enox";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
