this forceAddUniform "CUP_U_O_RUS_Flora_2_VDV";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "CUP_V_RUS_6B3_1";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 7 do {this addItemToVest "hlc_45Rnd_545x39_m_rpk";};
this addBackpack "CUP_B_AlicePack_Khaki";
for "_i" from 1 to 7 do {this addItemToBackpack "hlc_45Rnd_545x39_m_rpk";};
this addHeadgear "CUP_H_RUS_6B27";
this addWeapon "hlc_rifle_rpk74n";
this addWeapon "CUP_hgun_Makarov";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";