this forceAddUniform "CUP_U_O_RUS_Flora_2_VDV";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "CUP_V_O_Ins_Carrier_Rig_Light";
this addItemToVest "CUP_HandGrenade_RGD5";
this addItemToVest "SmokeShell";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addBackpack "CUP_B_AlicePack_Khaki";
this addItemToBackpack "ToolKit";
this addHeadgear "H_PilotHelmetHeli_O";
this addWeapon "hlc_rifle_aks74u";
this addWeapon "CUP_hgun_Makarov";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";