this forceAddUniform "CUP_U_O_RUS_Flora_2_VDV";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "CUP_V_RUS_6B3_1";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 9 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addBackpack "CUP_B_AlicePack_Khaki";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_GP25_M";};
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_GP25_M";};
for "_i" from 1 to 6 do {this addItemToBackpack "hlc_GRD_purple";};
this addHeadgear "CUP_H_RUS_Beret_VDV";
this addWeapon "hlc_rifle_aks74_GL";
this addWeapon "CUP_hgun_Makarov";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";