this forceAddUniform "CUP_U_O_RUS_Flora_2_VDV";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "CUP_V_RUS_6B3_1";
for "_i" from 1 to 9 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
this addItemToVest "SmokeShell";
this addBackpack "CUP_B_RPGPack_Khaki";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_PG7VM_M";};
this addItemToBackpack "CUP_OG7_M";
this addHeadgear "CUP_H_RUS_6B27";
this addWeapon "hlc_rifle_aks74";
this addWeapon "CUP_launch_RPG7V";
this addSecondaryWeaponItem "CUP_acc_rpg7_zero_50";
this addWeapon "CUP_hgun_Makarov";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";

