this forceAddUniform "U_O_CombatUniform_oucamo";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_HarnessOGL_gry";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 2 do {this addItemToVest "30Rnd_65x39_caseless_green_mag_Tracer";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 6 do {this addItemToVest "1Rnd_SmokeRed_Grenade_shell";};
this addBackpack "B_FieldPack_oucamo";
for "_i" from 1 to 2 do {this addItemToBackpack "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 6 do {this addItemToBackpack "SmokeShellBlue";};
for "_i" from 1 to 6 do {this addItemToBackpack "SmokeShellGreen";};
this addItemToBackpack "1Rnd_HE_Grenade_shell";
this addHeadgear "H_HelmetO_oucamo";
this addWeapon "arifle_Katiba_GL_F";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "hgun_Pistol_heavy_01_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";