this forceAddUniform "U_B_GEN_Soldier_F";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShellBlue";};
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShellGreen";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_M84";};
this addVest "V_TacVest_gen_F";
for "_i" from 1 to 8 do {this addItemToVest "50rnd_570x28_SMG_03";};
for "_i" from 1 to 3 do {this addItemToVest "6rnd_45ACP_Cylinder";};
this addHeadgear "H_Beret_gen_F";
this addWeapon "SMG_03C_black";
this addWeapon "hgun_Pistol_heavy_02_F";
this addWeapon "Rangefinder";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this addGoggles "G_Aviator";