this forceAddUniform "U_B_GEN_Commander_F";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_M84";};
this addVest "V_TacVest_gen_F";
for "_i" from 1 to 10 do {this addItemToVest "30Rnd_556x45_Stanag";};
this addHeadgear "MNP_Helmet_PAGST_BK";
this addWeapon "hlc_rifle_416D10";
this addPrimaryWeaponItem "optic_aco";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this addGoggles "G_Balaclava_lowprofile";
