this forceAddUniform "MNP_CombatUniform_RU_Med";
this addItemToUniform "16Rnd_9x21_Mag";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "MNP_Vest_RU_T2";
for "_i" from 1 to 3 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 3 do {this addItemToVest "SmokeShellRed";};
for "_i" from 1 to 10 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addBackpack "B_Kitbag_sgg";
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "MNP_Helmet_RU_LT";
this addGoggles "G_Bandanna_blk";
this addWeapon "hlc_rifle_aku12";
this addWeapon "CUP_hgun_Duty";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
