this forceAddUniform "MNP_CombatUniform_Ranger_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "CUP_V_B_Eagle_SPC_SL";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 4 do {this addItemToVest "CUP_20Rnd_762x51_B_SCAR";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_20Rnd_TE1_Red_Tracer_762x51_SCAR";};
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 5 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_Smoke_M203";};
this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";
this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";
this addHeadgear "CUP_H_CZ_Helmet07";
this addWeapon "CUP_arifle_Mk17_STD_EGLM_woodland";
this addPrimaryWeaponItem "CUP_muzzle_mfsup_Flashhider_762x51_Black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_CompM2_Woodland";
this addWeapon "Binocular";
this linkItem "ItemWatch";
this linkItem "ItemMap";
this linkItem "ItemCompass";