this forceAddUniform "U_B_T_Soldier_F";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_tna_F";
for "_i" from 1 to 9 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_FlareRed_M203";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
for "_i" from 1 to 2 do {this addItemToVest "9rnd_45ACP_Mag";};
this addHeadgear "H_HelmetB_Enh_tna_F";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "cup_optic_compm4";
this addWeapon "hgun_ACPC2_F";
this addWeapon "Rangefinder";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
