this forceAddUniform "U_B_T_Soldier_F";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_tna_F";
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
this addBackpack "B_ViperHarness_oli_F";
this addItemToBackpack "ToolKit";
this addHeadgear "H_HelmetB_tna_F";
this addWeapon "hlc_rifle_M4";
this addPrimaryWeaponItem "cup_optic_compm4";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";

