this forceAddUniform "U_C_ConstructionCoverall_Blue_F";
this addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 4 do {this addItemToUniform "hlc_15Rnd_9x19_B_P226";};
this addVest "CUP_V_B_LHDVest_Blue";
for "_i" from 1 to 4 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addBackpack "B_FieldPack_blk";
this addItemToBackpack "ToolKit";
this addHeadgear "CUP_H_CDF_Beret_UN";
this addWeapon "hlc_pistol_P226US";
this addGoggles "G_Shades_Blue";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";