comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

this forceAddUniform "CUP_I_B_PMC_Unit_34";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "SP_Tactical1_White";
for "_i" from 1 to 2 do {this addItemToVest "ACE_M84";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 10 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addBackpack "CFP_RPGPack_White";
this addItemToBackpack "ACE_EntrenchingTool";
this addItemToBackpack "CUP_PG7V_M";
this addHeadgear "SP_SSh68CoverHelmet_White1";
this addGoggles "G_Bandanna_blk";
this addWeapon "hlc_rifle_ak12";
this addWeapon "CUP_launch_RPG7V";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
