this forceAddUniform "CUP_I_B_PMC_Unit_27";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_PMC_CIRAS_Black_TL";
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_HandGrenade_M67";};
this addItemToBackpack "SmokeShell";
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_Smoke_M203";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_30Rnd_556x45_Stanag";};
this addHeadgear "H_HelmetSpecB_blk";
this addGoggles "G_Balaclava_combat";
this addWeapon "CUP_arifle_L85A2_GL";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
