this forceAddUniform "CUP_I_B_PMC_Unit_25";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addBackpack "CUP_B_USPack_Black";
for "_i" from 1 to 3 do {this addItemToBackpack "30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToBackpack "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_HandGrenade_M67";};
this addItemToBackpack "SmokeShell";
this addItemToBackpack "CUP_Javelin_M";
this addHeadgear "H_HelmetSpecB_blk";
this addGoggles "G_Balaclava_combat";
this addWeapon "CUP_arifle_L85A2";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_launch_Javelin";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";

