this forceAddUniform "CUP_U_O_Partisan_TTsKO_Mixed";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_30Rnd_545x39_AK_M";
this addVest "CUP_V_O_TK_Vest_1";
for "_i" from 1 to 5 do {this addItemToVest "CUP_30Rnd_545x39_AK_M";};
this addHeadgear "CUP_H_SLA_BeretRed";
this addWeapon "CUP_arifle_AK74";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
