this forceAddUniform "U_B_CTRG_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr_noflag_F";
this addBackpack "B_ViperLightHarness_oli_F";
for "_i" from 1 to 4 do {this addItemToBackpack "200rnd_556x45_Box_Red_F";};
this addHeadgear "H_HelmetB_TI_tna_F";
this addWeapon "hlc_lmg_minimipara_railed";
this addPrimaryWeaponItem "acc_pointer_ir";
this addPrimaryWeaponItem "optic_aco";
this addPrimaryWeaponItem "muzzle_snds_h_mg_blk_f";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";
this addGoggles "G_Balaclava_TI_G_tna_F";