this forceAddUniform "U_B_CTRG_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr_noflag_F";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30rnd_556x45_EPR_G36";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_30rnd_556x45_Tracers_G36";};
this addHeadgear "H_HelmetB_TI_tna_F";
this addWeapon "hlc_rifle_G36C";
this addPrimaryWeaponItem "acc_pointer_ir";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addPrimaryWeaponItem "muzzle_snds_m";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";
this addGoggles "G_Balaclava_TI_G_tna_F";