this forceAddUniform "U_B_T_Soldier_F";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_CableTie";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "Chemlight_red";
this addVest "V_PlateCarrier1_tna_F";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_65x39_caseless_mag";};
this addItemToVest "16Rnd_9x21_Mag";
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_65x39_caseless_mag_Tracer";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addBackpack "B_AssaultPack_tna_F";
for "_i" from 1 to 2 do {this addItemToBackpack "100Rnd_65x39_caseless_mag";};
for "_i" from 1 to 2 do {this addItemToBackpack "100Rnd_65x39_caseless_mag_Tracer";};
this addHeadgear "H_HelmetB_Enh_tna_F";
this addWeapon "arifle_MX_khk_F";
this addPrimaryWeaponItem "optic_Aco";
this addPrimaryWeaponItem "muzzle_snds_H_khk_F";
this addPrimaryWeaponItem "CUP_acc_XM8_light_module";
this addWeapon "hgun_P07_khk_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";