this forceAddUniform "U_BG_Guerilla2_2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_TacVest_oli";
this addItemToVest "HandGrenade";
this addItemToVest "SmokeShell";
this addItemToVest "200Rnd_65x39_cased_Box_Tracer";
this addBackpack "B_TacticalPack_rgr";
for "_i" from 1 to 2 do {this addItemToBackpack "200Rnd_65x39_cased_Box";};
this addHeadgear "CUP_H_SLA_Helmet";
this addWeapon "LMG_Mk200_F";
this addPrimaryWeaponItem "optic_Holosight";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
