this forceAddUniform "U_BG_leader";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_TacVest_blk";
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Yellow";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag";};
this addItemToVest "HandGrenade";
this addItemToVest "SmokeShell";
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
this addHeadgear "CUP_H_SLA_Helmet";
this addWeapon "arifle_TRG21_GL_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
