this forceAddUniform "U_BG_Guerilla1_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_TacVest_khk";
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Yellow";};
this addItemToVest "HandGrenade";
this addItemToVest "SmokeShell";
this addHeadgear "CUP_H_SLA_Helmet";
this addWeapon "arifle_TRG21_F";
this addPrimaryWeaponItem "optic_ACO_grn";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
