this forceAddUniform "CUP_U_B_BAF_MTP_S6_UnRolled";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "hlc_15Rnd_9x19_B_P226";
this addVest "V_PlateCarrierH_CTRG";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_9x19_SD_MP5";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellGreen";};
this addHeadgear "CUP_H_BAF_Helmet_Pilot";
this addGoggles "G_Bandanna_tan";
this addWeapon "hlc_smg_mp5sd6";
this addWeapon "hlc_pistol_P226R_Combat";
this addHandgunItem "acc_flashlight_pistol";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen5";
