this forceAddUniform "CUP_U_B_BAF_MTP_S3_RolledUp";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "hlc_15Rnd_9x19_B_P226";
this addVest "V_PlateCarrierL_CTRG";
this addItemToVest "ACE_bodyBag";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A2_HE";};
for "_i" from 1 to 7 do {this addItemToVest "hlc_30rnd_556x45_TDim";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_M14";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_Chemlight_IR";};
this addHeadgear "CUP_H_BAF_Helmet_3_MTP";
this addGoggles "G_Bandanna_tan";
this addWeapon "hlc_rifle_ACR_mid_tan";
this addPrimaryWeaponItem "muzzle_snds_m_snd_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "CUP_optic_CompM2_Desert";
this addWeapon "hlc_pistol_P226R_Combat";
this addHandgunItem "acc_flashlight_pistol";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen5";
