this forceAddUniform "MNP_CombatUniform_Scorpion_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "150Rnd_556x45_Drum_Mag_F";
this addVest "MNP_Vest_Scorpion_2";
for "_i" from 1 to 2 do {this addItemToVest "CUP_15Rnd_9x19_M9";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "ACE_Chemlight_HiRed";
this addItemToVest "150Rnd_556x45_Drum_Mag_F";
this addItemToVest "150Rnd_556x45_Drum_Mag_Tracer_F";
this addBackpack "B_Kitbag_rgr";
this addItemToBackpack "150Rnd_556x45_Drum_Mag_F";
this addItemToBackpack "150Rnd_556x45_Drum_Mag_Tracer_F";
this addHeadgear "MNP_Helmet_Scorpion";
this addGoggles "G_Bandanna_oli";
this addWeapon "arifle_SPAR_02_blk_F";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";