this forceAddUniform "MNP_CombatUniform_Scorpion_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACRE_PRC343";
this addVest "MNP_Vest_Scorpion_2";
for "_i" from 1 to 2 do {this addItemToVest "CUP_15Rnd_9x19_M9";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "ACE_Chemlight_HiRed";
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 3 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
this addBackpack "B_Kitbag_mcamo";
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 9 do {this addItemToBackpack "SmokeShellBlue";};
for "_i" from 1 to 9 do {this addItemToBackpack "SmokeShellGreen";};
this addItemToBackpack "SmokeShellOrange";
this addItemToBackpack "SmokeShellPurple";
for "_i" from 1 to 2 do {this addItemToBackpack "B_IR_Grenade";};
this addHeadgear "MNP_Helmet_Scorpion";
this addWeapon "arifle_SPAR_01_GL_blk_F";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "CUP_hgun_M9";
this addWeapon "Rangefinder";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";