this forceAddUniform "MNP_CombatUniform_Scorpion_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "1Rnd_Smoke_Grenade_shell";};
this addItemToUniform "SmokeShellGreen";
this addItemToUniform "SmokeShellBlue";
this addItemToUniform "SmokeShellRed";
this addVest "MNP_Vest_Scorpion_2";
this addItemToVest "CUP_15Rnd_9x19_M9";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "ACE_Chemlight_HiRed";
for "_i" from 1 to 5 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addBackpack "B_Carryall_mcamo";
this addItemToBackpack "CUP_Javelin_M";
this addHeadgear "MNP_Helmet_Scorpion";
this addWeapon "arifle_SPAR_01_GL_khk_F";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "CUP_hgun_M9";
this addWeapon "Rangefinder";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";