this forceAddUniform "MNP_CombatUniform_Scorpion_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACRE_PRC343";
this addVest "CUP_V_B_RRV_MG";
for "_i" from 1 to 3 do {this addItemToVest "CUP_15Rnd_9x19_M9";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_100Rnd_762x51_Barrier_M60E4";};
this addBackpack "B_FieldPack_khk";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_100Rnd_762x51_Barrier_M60E4";};
this addHeadgear "MNP_Helmet_Scorpion";
this addGoggles "G_Balaclava_combat";
this addWeapon "CUP_lmg_M240";
this addPrimaryWeaponItem "CUP_optic_ZDDot";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";