this forceAddUniform "MNP_CombatUniform_Scorpion_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACRE_PRC343";
this addVest "MNP_Vest_Olive_1";
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_15Rnd_9x19_M9";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "ACE_Chemlight_HiRed";
this addBackpack "B_TacticalPack_blk";
this addItemToBackpack "CUP_15Rnd_9x19_M9";
for "_i" from 1 to 2 do {this addItemToBackpack "MRAWS_HEAT_F";};
this addHeadgear "MNP_Helmet_Scorpion";
this addWeapon "arifle_SPAR_01_snd_F";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "launch_MRAWS_green_rail_F";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";