this forceAddUniform "CUP_U_B_BAF_DPM_S1_RolledUp";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "MineDetector";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "CUP_V_BAF_Osprey_Mk2_DPM_Soldier1";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 6 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A2_HE";};
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addHeadgear "CUP_H_BAF_Helmet_2_DPM";
this addWeapon "CUP_arifle_L85A2_NG";
this addWeapon "CUP_launch_NLAW";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
