this forceAddUniform "CUP_U_B_BAF_DPM_Tshirt";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "MineDetector";
this addVest "CUP_V_BAF_Osprey_Mk2_DPM_Sapper";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 6 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A2_HE";};
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addBackpack "CUP_B_Bergen_BAF";
this addItemToBackpack "ACE_DefusalKit";
this addItemToBackpack "ACE_M26_Clacker";
for "_i" from 1 to 2 do {this addItemToBackpack "DemoCharge_Remote_Mag";};
this addHeadgear "CUP_H_BAF_Helmet_3_DPM";
this addGoggles "G_Lowprofile";
this addWeapon "CUP_arifle_L85A2";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";