this forceAddUniform "U_O_CombatUniform_ocamo";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "10Rnd_9x21_Mag";
this addVest "V_HarnessO_brn";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "150Rnd_762x54_Box";};
this addBackpack "B_AssaultPack_ocamo";
for "_i" from 1 to 2 do {this addItemToBackpack "150Rnd_762x54_Box_Tracer";};
this addItemToBackpack "150Rnd_762x54_Box";
this addHeadgear "H_HelmetO_ocamo";
this addGoggles "G_Bandanna_khk";
this addWeapon "LMG_Zafir_F";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "hgun_Pistol_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
