this forceAddUniform "U_O_CombatUniform_ocamo";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "10Rnd_9x21_Mag";
this addVest "V_HarnessO_brn";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_65x39_caseless_green_mag_Tracer";};
this addBackpack "B_Carryall_ocamo";
for "_i" from 1 to 3 do {this addItemToBackpack "RPG32_F";};
this addHeadgear "H_HelmetO_ocamo";
this addWeapon "arifle_Katiba_F";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "launch_RPG32_F";
this addWeapon "hgun_Pistol_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
