this forceAddUniform "U_B_CTRG_Soldier_urb_1_F";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr_noflag_F";
for "_i" from 1 to 2 do {this addItemToVest "200Rnd_556x45_Box_Tracer_Red_F";};
this addBackpack "B_ViperHarness_oli_F";
for "_i" from 1 to 3 do {this addItemToBackpack "200Rnd_556x45_Box_Tracer_Red_F";};
this addHeadgear "H_HelmetB_TI_tna_F";
this addWeapon "hlc_lmg_mk46";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addPrimaryWeaponItem "acc_pointer_ir";
this addPrimaryWeaponItem "muzzle_snds_h_mg_blk_f";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkitem "arcore_nightvision_Gen8";
this addGoggles "G_Balaclava_TI_G_tna_F";