this forceAddUniform "U_B_CTRG_Soldier_urb_1_F";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr_noflag_F";
for "_i" from 1 to 7 do {this addItemToVest "30rnd_556x45_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30rnd_556x45_S_L5";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_FlareGreen_M203";};
for "_i" from 1 to 2 do {this addItemToVest "UGL_FlareCIR_F";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addItemToVest "30rnd_9x21_Yellow_Mag";
this addHeadgear "H_HelmetB_TI_tna_F";
this addGoggles "G_Balaclava_TI_G_tna_F";
this addWeapon "hlc_rifle_416D145_gl";
this addPrimaryWeaponItem "cup_optic_holoblack";
this addPrimaryWeaponItem "muzzle_snds_m";
this addPrimaryWeaponItem "acc_pointer_ir";
this addWeapon "hgun_P07_khk_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkitem "arcore_nightvision_Gen8";

