this forceAddUniform "rhs_uniform_g3_mc";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "rhsusf_mbav_rifleman";
for "_i" from 1 to 4 do {this addItemToVest "rhs_30Rnd_762x39mm";};
for "_i" from 1 to 6 do {this addItemToVest "rhs_30Rnd_762x39mm_tracer";};
this addBackpack "rhsusf_falconii_mc";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_100Rnd_762x54mmR";};
this addItemToBackpack "rhs_mag_9x19_17";
this addItemToBackpack "rhs_mag_rgd5";
this addItemToBackpack "rhs_mag_rdg2_white";
this addHeadgear "rhsusf_opscore_mc_cover_pelt";
this addGoggles "rhsusf_shemagh_gogg_tan";
this addWeapon "rhs_weap_ak103_zenitco01_b33_grip1";
this addPrimaryWeaponItem "rhs_acc_dtk1";
this addPrimaryWeaponItem "rhs_acc_perst3_2dp_light_h";
this addPrimaryWeaponItem "rhsusf_acc_eotech_xps3";
this addPrimaryWeaponItem "rhsusf_acc_grip1";
this addWeapon "rhs_weap_pya";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";