this forceAddUniform "rhs_uniform_g3_mc";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "rhsusf_mbav_grenadier";
for "_i" from 1 to 6 do {this addItemToVest "rhs_30Rnd_762x39mm";};
this addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 4 do {this addItemToVest "rhs_30Rnd_762x39mm_tracer";};
this addItemToVest "rhs_mag_9x19_17";
this addBackpack "rhsusf_falconii_mc";
for "_i" from 1 to 6 do {this addItemToBackpack "rhs_VOG25";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_rdg2_white";};
this addItemToBackpack "SmokeShellGreen";
this addHeadgear "rhsusf_opscore_mc_cover_pelt_cam";
this addGoggles "rhs_googles_black";
this addWeapon "rhs_weap_ak103_gp25_npz";
this addPrimaryWeaponItem "rhs_acc_dtk1";
this addPrimaryWeaponItem "rhsusf_acc_T1_low";
this addWeapon "rhs_weap_pya";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";