this forceAddUniform "rhs_uniform_g3_mc";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "rhsusf_mbav_medic";
for "_i" from 1 to 6 do {this addItemToVest "rhs_30Rnd_762x39mm";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_30Rnd_762x39mm_tracer";};
this addItemToVest "rhs_mag_9x19_17";
this addBackpack "B_Carryall_cbr";
for "_i" from 1 to 50 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addItemToBackpack "rhs_mag_m18_green";
this addItemToBackpack "rhs_mag_m18_purple";
this addItemToBackpack "rhs_mag_m18_red";
this addHeadgear "rhsusf_opscore_mc_cover_pelt_cam";
this addGoggles "rhsusf_shemagh2_gogg_tan";
this addWeapon "rhs_weap_ak103_zenitco01_b33_grip1";
this addPrimaryWeaponItem "rhs_acc_dtk1";
this addPrimaryWeaponItem "rhs_acc_perst3_2dp_light_h";
this addPrimaryWeaponItem "rhsusf_acc_T1_low";
this addPrimaryWeaponItem "rhsusf_acc_grip1";
this addWeapon "rhs_weap_pya";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";