this forceAddUniform "CUP_U_B_FR_DirAction";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_15Rnd_9x19_M9";
this addVest "CUP_V_B_RRV_MG";
for "_i" from 1 to 2 do {this addItemToVest "CUP_200Rnd_TE4_Red_Tracer_556x45_M249";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 1 do {this addItemToVest "HandGrenade";};
this addBackpack "CUP_B_USMC_AssaultPack";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_200Rnd_TE4_Red_Tracer_556x45_M249";};
this addHeadgear "CUP_H_FR_BoonieMARPAT";
this addWeapon "CUP_lmg_m249_pip4";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";