this forceAddUniform "CUP_U_B_FR_Scout3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_15Rnd_9x19_M9";
this addVest "CUP_V_B_RRV_Scout";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 1 do {this addItemToVest "HandGrenade";};
this addHeadgear "CUP_H_FR_BoonieMARPAT";
this addWeapon "CUP_arifle_M4A1_camo";
this addPrimaryWeaponItem "CUP_acc_Flashlight_wdl";
this addPrimaryWeaponItem "CUP_optic_HoloWdl";
this addWeapon "CUP_launch_M72A6";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
