this forceAddUniform "CUP_U_B_USMC_MARPAT_WDL_TwoKneepads";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_15Rnd_9x19_M9";
this addVest "CUP_V_B_MTV";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
this addBackpack "CUP_B_USMC_AssaultPack";
this addItemToBackpack "ToolKit";
this addHeadgear "CUP_H_USMC_Crew_Helmet";
this addWeapon "CUP_arifle_M4A1";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";