this forceAddUniform "U_B_T_Soldier_F";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_CableTie";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "Chemlight_red";
this addVest "V_PlateCarrierGL_tna_F";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
this addItemToVest "1Rnd_Smoke_Grenade_shell";
this addItemToVest "1Rnd_SmokeRed_Grenade_shell";
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_65x39_caseless_mag";};
this addItemToVest "16Rnd_9x21_Mag";
this addItemToVest "30Rnd_65x39_caseless_mag_Tracer";
this addItemToVest "SmokeShellRed";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addBackpack "B_AssaultPack_tna_F";
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "30Rnd_65x39_caseless_mag_Tracer";};
this addHeadgear "H_HelmetB_Enh_tna_F";
this addWeapon "arifle_MX_GL_khk_F";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "hgun_P07_khk_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";