this forceAddUniform "rhs_uniform_m88_patchless";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhs_6b23_ML_medic";
this addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_white";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_30Rnd_545x39_AK";};
for "_i" from 1 to 3 do {this addItemToVest "rhs_30Rnd_545x39_AK_no_tracers";};
this addBackpack "rhs_assault_umbts";
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 6 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "rhs_6b27m_ml";
this addWeapon "rhs_weap_aks74u";
this addPrimaryWeaponItem "rhs_acc_dtk1983";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";