this forceAddUniform "rhs_uniform_m88_patchless";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhs_6b23_ML_6sh92";
for "_i" from 1 to 4 do {this addItemToVest "rhs_30Rnd_545x39_AK";};
for "_i" from 1 to 4 do {this addItemToVest "rhs_30Rnd_545x39_7N6_AK";};
this addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_white";};
this addBackpack "rhs_rpg_empty";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_rpg7_PG7V_mag"};
this addHeadgear "rhs_6b27m_ml_ess";
this addWeapon "rhs_weap_ak74n";
this addPrimaryWeaponItem "rhs_acc_dtk1983";
this addWeapon "rhs_weap_rpg7";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
