this forceAddUniform "MNP_CombatUniform_RO2_Sh";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Fortify";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_UKR_A";
this addItemToVest "10Rnd_9x21_Mag";
for "_i" from 1 to 8 do {this addItemToVest "hlc_45Rnd_545x39_t_rpk";};
this addBackpack "CUP_B_RUS_Backpack";
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_Chemlight_HiRed";};
this addItemToBackpack "CUP_HandGrenade_RGO";
for "_i" from 1 to 3 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_HandFlare_Red";};
for "_i" from 1 to 8 do {this addItemToBackpack "hlc_45Rnd_545x39_t_rpk";};
this addHeadgear "CUP_H_RUS_ZSH_1";
this addWeapon "hlc_rifle_RPK12";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_MRad";
this addWeapon "hgun_Pistol_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
