this forceAddUniform "U_B_CombatUniform_mcam";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "HandGrenade";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
this addVest "V_PlateCarrier1_rgr";
for "_i" from 1 to 3 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 4 do {this addItemToVest "100Rnd_65x39_caseless_mag_Tracer";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 6 do {this addItemToBackpack "100Rnd_65x39_caseless_mag_Tracer";};
this addHeadgear "H_HelmetSpecB_sand";
this addWeapon "arifle_MX_SW_Black_F";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "optic_Holosight";
this addPrimaryWeaponItem "bipod_01_F_snd";
this addWeapon "hgun_P07_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen5";
