this forceAddUniform "MNP_CombatUniform_Australia_S";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_Eagle_SPC_AR";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_556x45_T_AUG";};
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_556x45_B_AUG";};
this addBackpack "B_Kitbag_cbr";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
for "_i" from 1 to 5 do {this addItemToBackpack "hlc_100Rnd_762x51_M_M60E4";};
this addHeadgear "CUP_H_FR_ECH";
this addWeapon "hlc_rifle_auga2_t";
this addPrimaryWeaponItem "optic_Aco";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
