this forceAddUniform "MNP_CombatUniform_Australia_S";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_Eagle_SPC_MG";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
this addBackpack "CUP_B_USPack_Coyote";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_100Rnd_762x51_M_M60E4";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
this addHeadgear "CUP_H_FR_ECH";
this addWeapon "hlc_lmg_mk48mod1";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";