this forceAddUniform "MNP_CombatUniform_Australia_S";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_Eagle_SPC_TL";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
this addItemToVest "SmokeShellOrange";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_556x45_B_AUG";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30Rnd_556x45_T_AUG";};
this addBackpack "B_FieldPack_cbr";
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeBlue_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
this addHeadgear "CUP_H_FR_ECH";
this addWeapon "hlc_rifle_auga3_GL_B";
this addWeapon "Binocular";
this addPrimaryWeaponItem "optic_Aco";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";