this forceAddUniform "MNP_CombatUniform_Australia_S";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "hlc_30Rnd_556x45_T_AUG";
this addVest "CUP_V_B_Eagle_SPC_AT";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30Rnd_556x45_B_AUG";};
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_556x45_T_AUG";};
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
this addHeadgear "CUP_H_FR_ECH";
this addWeapon "hlc_rifle_auga2_t";
this addPrimaryWeaponItem "CUP_optic_CompM2_Black";
this addWeapon "CUP_launch_M136";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
