this forceAddUniform "CUP_U_B_US_BDU_OD";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addVest "CUP_V_O_SLA_M23_1_OD";
for "_i" from 1 to 8 do {this addItemToVest "CUP_30Rnd_762x39_AK47_M";};
this addItemToVest "CUP_HandGrenade_RGD5";
this addItemToVest "SmokeShell";
this addBackpack "CUP_B_AlicePack_OD";
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "CUP_H_SLA_Helmet_URB";
this addWeapon "CUP_arifle_AK47_Early";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this addItemToUniform "ACE_Flashlight_XL50"