this forceAddUniform "CUP_U_B_US_BDU_OD";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addVest "CUP_V_O_SLA_M23_1_OD";
for "_i" from 1 to 8 do {this addItemToVest "CUP_30Rnd_762x39_AK47_M";};
this addItemToVest "CUP_HandGrenade_RGD5";
this addItemToVest "SmokeShell";
this addBackpack "CUP_B_AlicePack_OD";
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_GP25_M";};
this addHeadgear "CUP_H_US_patrol_cap_OD";
this addWeapon "CUP_arifle_AK47_GL";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this addWeapon "Binocular";
this addItemToUniform "ACE_Flashlight_XL50"