this forceAddUniform "U_O_CombatUniform_oucamo";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Fortify";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "MiniGrenade";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
this addVest "V_HarnessO_gry";
for "_i" from 1 to 3 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 2 do {this addItemToVest "150Rnd_762x54_Box_Tracer";};
this addBackpack "B_FieldPack_oucamo";
for "_i" from 1 to 4 do {this addItemToBackpack "150Rnd_762x54_Box_Tracer";};
this addHeadgear "H_HelmetO_oucamo";
this addWeapon "LMG_Zafir_F";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "optic_ACO_grn";
this addWeapon "hgun_Rook40_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen5";
