this forceAddUniform "U_O_CombatUniform_oucamo";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Fortify";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "MiniGrenade";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
this addVest "V_HarnessOGL_gry";
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_65x39_caseless_green_mag_Tracer";};
this addBackpack "B_FieldPack_oucamo";
for "_i" from 1 to 3 do {this addItemToBackpack "16Rnd_9x21_Mag";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "UGL_FlareGreen_F";};
for "_i" from 1 to 5 do {this addItemToBackpack "UGL_FlareRed_F";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "H_HelmetO_oucamo";
this addWeapon "arifle_Katiba_GL_F";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "optic_ACO_grn";
this addWeapon "hgun_Rook40_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen5";
