this forceAddUniform "U_B_CTRG_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_30Rnd_TE1_Yellow_Tracer_762x39_bakelite_AK103_M";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_RGD5";};
this addVest "V_PlateCarrierIAGL_oli";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_TE1_Yellow_Tracer_762x39_bakelite_AK103_M";};
this addBackpack "B_Carryall_khk";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_PG7VM_M";};
this addHeadgear "SP_SSh68Helmet_Green1";
this addWeapon "CUP_arifle_AK103";
this addPrimaryWeaponItem "CUP_optic_Kobra";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";