this forceAddUniform "U_BG_Guerilla2_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "16Rnd_9x21_Mag";
this addVest "V_PlateCarrier1_blk";
for "_i" from 1 to 2 do {this addItemToVest "200Rnd_65x39_cased_Box_Tracer";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_AssaultPack_blk";
this addHeadgear "H_HelmetCrew_I";
this addGoggles "G_Balaclava_lowprofile";
this addWeapon "LMG_Mk200_F";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "hgun_Rook40_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
