this forceAddUniform "U_O_CombatUniform_oucamo";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "16Rnd_9x21_Mag";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "CUP_V_CDF_6B3_1_SNW";
for "_i" from 1 to 1 do {this addItemToVest "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_545x39_AK74M_M";};
this addBackpack "B_Carryall_oucamo";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_GP25_M";};
this addHeadgear "H_HelmetO_oucamo";
this addGoggles "G_Bandanna_blk";
this addWeapon "CUP_arifle_AK74M_GL_top_rail";
this addPrimaryWeaponItem "CUP_optic_MicroT1_low";
this addWeapon "CUP_hgun_Duty";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
