this forceAddUniform "MNP_CombatUniform_Canada_S";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_Canada_T2";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_12Rnd_40sw_JHP_P226";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200rnd_556x45_M_SAW";};
this addItemToBackpack "hlc_200rnd_556x45_B_SAW";
this addHeadgear "MNP_Helmet_UN";
this addWeapon "hlc_lmg_minimipara_long_railed";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P226R_40Elite";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";