
this forceAddUniform "MNP_CombatUniform_Canada_S";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EarPlugs";
this addVest "MNP_Vest_Canada_T2";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_12Rnd_40sw_JHP_P226";};
for "_i" from 1 to 7 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30rnd_556x45_M";};
this addItemToVest "SmokeShellPurple";
this addBackpack "B_Carryall_oli";
for "_i" from 1 to 4 do {this addItemToBackpack "MRAWS_HEAT_F";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
for "_i" from 1 to 7 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
this addHeadgear "MNP_Helmet_UN";
this addGoggles "G_Bandanna_oli";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P226R_40Elite";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";