this forceAddUniform "skn_u_nbc_opf_yellow";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_PlateCarrier1_blk";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_MDim";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_17Rnd_9x19_glock17";};
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
this addBackpack "B_TacticalPack_blk";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 25 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_salineIV_500";};
this addHeadgear "H_HelmetB_light_black";
this addGoggles "skn_m04_gas_mask_blk";
this addWeapon "hlc_rifle_RU556";
this addPrimaryWeaponItem "hlc_muzzle_556NATO_KAC";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_Glock17";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";

