this forceAddUniform "CUP_U_B_BAF_DDPM_S1_RolledUp";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_17Rnd_9x19_glock17";};
this addVest "CUP_V_BAF_Osprey_Mk2_DDPM_Soldier1";
this addItemToVest "CUP_HandGrenade_L109A2_HE";
this addItemToVest "SmokeShell";
this addItemToVest "CUP_200Rnd_TE4_Red_Tracer_556x45_L110A1";
this addBackpack "CUP_B_Bergen_BAF";
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_200Rnd_TE4_Red_Tracer_556x45_L110A1";};
this addHeadgear "CUP_H_BAF_Helmet_4_DDPM";
this addWeapon "CUP_lmg_L110A1";
this addPrimaryWeaponItem "CUP_optic_Eotech533Grey";
this addWeapon "CUP_hgun_Glock17_tan";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
