this forceAddUniform "CUP_U_B_BAF_DDPM_S1_RolledUp";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
this addVest "CUP_V_BAF_Osprey_Mk2_DDPM_Officer";
for "_i" from 1 to 8 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_1Rnd_HE_M203";};
this addBackpack "CUP_B_Bergen_BAF";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_Smoke_M203";};
for "_i" from 1 to 5 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_M203";};
for "_i" from 1 to 5 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "Laserbatteries";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokePurple_Grenade_shell";};
this addHeadgear "CUP_H_BAF_Helmet_4_DDPM";
this addWeapon "CUP_arifle_L85A2_GL";
this addPrimaryWeaponItem "CUP_optic_Eotech533Grey";
this addWeapon "CUP_hgun_Glock17_tan";
this addWeapon "Laserdesignator";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";