this forceAddUniform "CUP_U_B_BAF_DDPM_Tshirt";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
this addVest "CUP_V_BAF_Osprey_Mk2_DDPM_Empty";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30Rnd_9x19_B_MP5";};
this addHeadgear "CUP_H_BAF_Helmet_Pilot";
this addWeapon "hlc_smg_mp5a3";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";