this forceAddUniform "MNP_CombatUniform_NOR_D_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
this addVest "MNP_Vest_Olive_1";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_M";};
for "_i" from 1 to 4 do {this addItemToVest "ACE_M84";};
for "_i" from 1 to 4 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 6 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_200rnd_556x45_M_SAW";};
this addHeadgear "CUP_H_USArmy_Helmet_ECH1_Green";
this addGoggles "G_Bandanna_oli";
this addWeapon "hlc_rifle_CQBR";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2";
this addPrimaryWeaponItem "CUP_optic_CompM2_Black";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
