this forceAddUniform "MNP_CombatUniform_US3Co_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "hlc_15Rnd_9x19_JHP_P226";
this addVest "MNP_Vest_NZ_2";
for "_i" from 1 to 4 do {this addItemToVest "ACE_M84";};
for "_i" from 1 to 4 do {this addItemToVest "SmokeShell";};
this addItemToVest "hlc_200rnd_556x45_M_SAW";
this addBackpack "CUP_B_USPack_Coyote";
this addItemToBackpack "hlc_200rnd_556x45_T_SAW";
this addItemToBackpack "hlc_200rnd_556x45_M_SAW";
this addHeadgear "CUP_H_FR_ECH";
this addWeapon "hlc_lmg_mk46";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "hlc_pistol_P226R";
this addHandgunItem "hlc_acc_TLR1";
this addHandgunItem "HLC_optic_Siglite";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
