this forceAddUniform "MNP_CombatUniform_US3Co_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "hlc_15Rnd_9x19_JHP_P226";
this addVest "MNP_Vest_NZ_2";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_M";};
for "_i" from 1 to 4 do {this addItemToVest "ACE_M84";};
for "_i" from 1 to 6 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addBackpack "CUP_B_USPack_Coyote";
for "_i" from 1 to 5 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 5 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 5 do {this addItemToBackpack "SmokeShellPurple";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "CUP_H_FR_ECH";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "hlc_pistol_Mk25";
this addHandgunItem "hlc_acc_TLR1";
this addHandgunItem "HLC_optic_Siglite";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
