this forceAddUniform "skn_u_nbc_bluf_mtp";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
this addVest "usm_vest_pasgtdes_lbv_rm_m";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addBackpack "CUP_B_USMC_MOLLE_WDL";
this addItemToBackpack "CUP_Javelin_M";
this addHeadgear "CUP_H_RACS_Helmet_olive";
this addGoggles "skn_m04_gas_mask_gre";
this addWeapon "CUP_arifle_Mk16_STD_SFG_black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_launch_Javelin";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemGPS";
this linkItem "ItemWatch";

