this forceAddUniform "CUP_U_B_USMC_Officer";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet"; 
this addItemToUniform "ACE_CableTie";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CUP_V_I_RACS_Carrier_Vest_2";
for "_i" from 1 to 6 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 10 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addBackpack "CUP_B_USMC_AssaultPack";
for "_i" from 1 to 10 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 10 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "CUP_H_USMC_Headset_HelmetWDL";
this addWeapon "CUP_arifle_Mk16_STD_EGLM_black";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";