this forceAddUniform "SP_0000_Standard_Coverall_Green";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_CableTie";};
this addVest "CFP_FAPC_MG_Multicam";
for "_i" from 1 to 5 do {this addItemToVest "CUP_100Rnd_TE1_Red_Tracer_556x45_BetaCMag";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_17Rnd_9x19_glock17";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToVest "ACE_M84";};
this addBackpack "CFP_AssaultPack_Multicam";
this addHeadgear "CFP_OPS2017_Helmet_Multicam2";
this addGoggles "G_Bandanna_blk";
this addWeapon "hlc_rifle_M27IAR";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Top_Flashlight_Black_L";
this addPrimaryWeaponItem "CUP_optic_CompM2_low";
this addPrimaryWeaponItem "HLC_bipod_UTGShooters";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addWeapon "CUP_hgun_Glock17";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this addHandgunItem "CUP_17Rnd_9x19_glock17";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
