this forceAddUniform "SP_0000_Standard_Coverall_Green";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_CableTie";};
this addVest "CFP_FAPC_Operator_Multicam";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30rnd_556x45_M";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_17Rnd_9x19_glock17";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToVest "ACE_M84";};
this addItemToVest "ACE_M26_Clacker";
this addItemToVest "MineDetector";
this addBackpack "CFP_AssaultPack_Multicam";
for "_i" from 1 to 2 do {this addItemToBackpack "SatchelCharge_Remote_Mag";};
this addHeadgear "CFP_OPS2017_Helmet_Multicam2";
this addGoggles "SP_Goggles_Tan";
this addWeapon "hlc_rifle_CQBR";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Top_Flashlight_Black_L";
this addPrimaryWeaponItem "CUP_optic_Eotech553_Black";
this addWeapon "CUP_hgun_Glock17";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this addHandgunItem "CUP_17Rnd_9x19_glock17";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
