this forceAddUniform "SP_0000_Standard_Coverall_Green";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_CableTie";};
this addVest "CFP_FAPC_Operator_Multicam";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30rnd_556x45_M";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_17Rnd_9x19_glock17";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToVest "ACE_M84";};
this addBackpack "SP_Carryall_Tan";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addItemToBackpack "ACE_bodyBag";
this addHeadgear "VSM_OPS2017_Helmet_Tan";
this addGoggles "CUP_G_Oakleys_Embr";
this addWeapon "hlc_rifle_CQBR";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Top_Flashlight_Black_L";
this addPrimaryWeaponItem "CUP_optic_MicroT1";
this addWeapon "CUP_hgun_Glock17";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this addHandgunItem "CUP_17Rnd_9x19_glock17";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
