this forceAddUniform "usm_bdu_odg";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addVest "CUP_V_CDF_OfficerBelt";
for "_i" from 1 to 4 do {this addItemToVest "CUP_7Rnd_45ACP_1911";};
this addBackpack "usm_pack_st138_prc77";
this addHeadgear "CUP_H_USMC_Helmet_Pilot";
this addWeapon "CUP_hgun_Colt1911";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";