this forceAddUniform "rhs_uniform_FROG01_wd";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Chemlight_HiRed";
this addItemToUniform "rhsusf_mag_15Rnd_9x19_JHP";
this addVest "rhsusf_mbav_mg";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_100Rnd_762x51_m61_ap";};
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_100Rnd_762x51";};
this addHeadgear "rhsusf_lwh_helmet_marpatwd";
this addWeapon "rhs_weap_m240B";
this addWeapon "rhsusf_weap_m9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
