this forceAddUniform "CUP_U_O_SLA_MixedCamo";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToUniform "hlc_15Rnd_9x19_B_P226";};
this addVest "CUP_V_CZ_vest04";
for "_i" from 1 to 3 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addHeadgear "CUP_H_USMC_Crew_Helmet";
this addWeapon "hlc_rifle_M4";
this addWeapon "hlc_pistol_Mk25";
this addHandgunItem "HLC_Optic_Docter_CADEX";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
