this forceAddUniform "usm_bdu_odg";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addVest "usm_vest_pasgt_lbv_rm_m";
for "_i" from 1 to 9 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addBackpack "usm_pack_alice_medic";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addItemToVest "SmokeShell";
this addHeadgear "usm_helmet_pasgt_w_m";
this addWeapon "RH_M16A2";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
