this forceAddUniform "usm_bdu_odg";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_tourniquet";
this addVest "usm_vest_lbv_rmp_m";
for "_i" from 1 to 5 do {this addItemToVest "hlc_20Rnd_762x51_B_M14";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 3 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_7Rnd_45ACP_1911";};
this addHeadgear "usm_bdu_8point_odg";
this addWeapon "hlc_rifle_M21_Rail";
this addPrimaryWeaponItem "optic_MRCO";
this addWeapon "CUP_hgun_Colt1911";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
