this forceAddUniform "U_B_T_Soldier_SL_F";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_CableTie";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "Chemlight_red";
this addVest "V_PlateCarrier1_tna_F";
for "_i" from 1 to 4 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_65x39_caseless_mag";};
this addItemToVest "16Rnd_9x21_Mag";
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_65x39_caseless_mag_Tracer";};
this addItemToVest "HandGrenade";
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 38 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 19 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShellGreen";};
this addItemToBackpack "SmokeShellRed";
this addItemToBackpack "HandGrenade";
this addHeadgear "H_HelmetB_Enh_tna_F";
this addWeapon "arifle_MX_khk_F";
this addPrimaryWeaponItem "optic_Aco";
this addPrimaryWeaponItem "muzzle_snds_H_khk_F";
this addPrimaryWeaponItem "CUP_acc_XM8_light_module";
this addWeapon "hgun_P07_khk_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";