removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this forceAddUniform "CUP_U_B_BAF_MTP_S1_RolledUp";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_17Rnd_9x19_glock17";};
this addVest "CUP_V_BAF_Osprey_Mk4_MTP_MachineGunner";
this addItemToVest "CUP_HandGrenade_L109A2_HE";
this addItemToVest "SmokeShell";
for "_i" from 1 to 2 do {this addItemToVest "CUP_200Rnd_TE4_Red_Tracer_556x45_L110A1";};
this addBackpack "CUP_B_Bergen_BAF";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_200Rnd_TE4_Red_Tracer_556x45_L110A1";};
this addHeadgear "CUP_H_BAF_Helmet_4_MTP";
this addWeapon "hlc_lmg_minimi_railed";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";