removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this addWeapon "arifle_MX_Black_F";
this addPrimaryWeaponItem "optic_Aco";
this addPrimaryWeaponItem "30Rnd_65x39_caseless_black_mag";
this forceAddUniform "U_BG_Guerilla2_3";
this addVest "V_PlateCarrier1_blk";
this addBackpack "B_AssaultPack_blk";
this addWeapon "Binocular";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "HandGrenade";
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_65x39_caseless_black_mag";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_HelmetSpecB_blk";
this addGoggles "G_Lowprofile";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
