removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this addWeapon "arifle_MX_GL_Black_F";
this addPrimaryWeaponItem "optic_Aco";
this addPrimaryWeaponItem "1Rnd_HE_Grenade_shell";
this addPrimaryWeaponItem "30Rnd_65x39_caseless_black_mag";
this addWeapon "hgun_Rook40_F";
this addHandgunItem "16Rnd_9x21_Mag";
this forceAddUniform "U_BG_Guerrilla_6_1";
this addVest "V_PlateCarrier2_blk";
this addBackpack "B_Carryall_khk";
this addWeapon "Binocular";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "16Rnd_9x21_Mag";};
for "_i" from 1 to 2 do {this addItemToVest "30Rnd_65x39_caseless_black_mag";};
for "_i" from 1 to 10 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 10 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
for "_i" from 1 to 10 do {this addItemToBackpack "SmokeShellPurple";};
this addHeadgear "H_HelmetSpecB_snakeskin";
this addGoggles "G_Lowprofile";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";