removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this addWeapon "arifle_MX_GL_Black_F";
this addPrimaryWeaponItem "optic_Aco";
this addPrimaryWeaponItem "30Rnd_65x39_caseless_black_mag";
this addPrimaryWeaponItem "1Rnd_HE_Grenade_shell";
this forceAddUniform "U_BG_Guerilla2_2";
this addVest "V_PlateCarrier1_blk";
this addBackpack "B_AssaultPack_blk";
this addWeapon "Binocular";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "1Rnd_HE_Grenade_shell";
this addItemToUniform "HandGrenade";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_65x39_caseless_black_mag";};
for "_i" from 1 to 6 do {this addItemToBackpack "3Rnd_HE_Grenade_shell";};
this addHeadgear "H_HelmetSpecB_snakeskin";
this addGoggles "G_Lowprofile";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
