removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this addWeapon "srifle_EBR_F";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addPrimaryWeaponItem "20Rnd_762x51_Mag";
this forceAddUniform "U_BG_Guerilla2_3";
this addVest "V_PlateCarrier1_blk";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
this addItemToUniform "HandGrenade";
this addItemToUniform "SmokeShellYellow";
for "_i" from 1 to 7 do {this addItemToVest "20Rnd_762x51_Mag";};
this addHeadgear "H_HelmetSpecB";
this addGoggles "G_Lowprofile";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
