removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this addWeapon "arifle_MX_Black_F";
this addPrimaryWeaponItem "optic_Aco";
this addPrimaryWeaponItem "30Rnd_65x39_caseless_black_mag";
this addWeapon "launch_MRAWS_green_rail_F";
this addSecondaryWeaponItem "MRAWS_HEAT_F";
this forceAddUniform "U_BG_Guerilla2_3";
this addVest "V_PlateCarrier1_blk";
this addBackpack "B_AssaultPack_blk";
this addWeapon "Binocular";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "HandGrenade";
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_65x39_caseless_black_mag";};
for "_i" from 1 to 2 do {this addItemToBackpack "MRAWS_HEAT55_F";};
this addItemToBackpack "MRAWS_HE_F";
this addHeadgear "H_HelmetSpecB";
this addGoggles "G_Lowprofile";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";