this forceAddUniform "MNP_CombatUniform_Finarctic_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_17Rnd_9x19_glock17";};
this addVest "MNP_Vest_FIN_1";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
this addItemToVest "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M";
this addBackpack "MNP_B_RUW_CA";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M";};
this addHeadgear "MNP_Helmet_FIN_A";
this addGoggles "CUP_PMC_Facewrap_Winter";
this addWeapon "CUP_lmg_Pecheneg";
this addPrimaryWeaponItem "CUP_optic_PechenegScope";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
