this forceAddUniform "MNP_CombatUniform_Finarctic_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_17Rnd_9x19_glock17";};
this addItemToUniform "CUP_30Rnd_762x39_AK103_bakelite_M";
this addVest "MNP_Vest_FIN_1";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_762x39_AK103_bakelite_M";};
this addBackpack "MNP_B_RUW_FP";
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_FlareWhite_GP25_M";};
this addHeadgear "MNP_Helmet_FIN_A";
this addGoggles "CUP_PMC_Facewrap_Winter";
this addWeapon "CUP_arifle_AK103_GL_railed";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Flashlight_Black_L";
this addPrimaryWeaponItem "CUP_optic_ZeissZPoint";
this addWeapon "CUP_hgun_Glock17_blk";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
