this forceAddUniform "MNP_CombatUniform_Finarctic_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_17Rnd_9x19_glock17";};
this addVest "MNP_Vest_FIN_1";
for "_i" from 1 to 8 do {this addItemToVest "CUP_30Rnd_762x39_AK103_bakelite_M";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "MNP_B_RUW_CA";
for "_i" from 1 to 3 do {this addItemToBackpack "DemoCharge_Remote_Mag";};
this addHeadgear "MNP_Helmet_FIN_A";
this addGoggles "CUP_PMC_Facewrap_Winter";
this addWeapon "CUP_arifle_AK103_railed";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Flashlight_Black_L";
this addPrimaryWeaponItem "CUP_optic_ZeissZPoint";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
