this forceAddUniform "MNP_CombatUniform_RU_Med_DB";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_CableTie";
this addVest "MNP_Vest_RU_D";
for "_i" from 1 to 6 do {this addItemToVest "CUP_30Rnd_TE1_Yellow_Tracer_762x39_bakelite_AK103_M";};
this addBackpack "MNP_B_Carryall_PLA_Basic_D";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Yellow_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_30Rnd_TE1_Yellow_Tracer_762x39_bakelite_AK103_M";};
this addHeadgear "MNP_Helmet_BLK";
this addWeapon "CUP_arifle_AK103";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";