this forceAddUniform "MNP_CombatUniform_RU_Med_DB";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_CableTie";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_RGD5";};
this addVest "MNP_Vest_RU_D";
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_TE1_Yellow_Tracer_762x39_bakelite_AK103_M";};
this addHeadgear "MNP_Helmet_BLK";
this addWeapon "CUP_arifle_AK103";
this addPrimaryWeaponItem "CUP_optic_Kobra";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";