this forceAddUniform "usm_bdu_odg";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addVest "usm_vest_rba_lbe_mg";
for "_i" from 1 to 3 do {this addItemToVest "CUP_7Rnd_45ACP_1911";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "SmokeShellRed";};
for "_i" from 1 to 3 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 8 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 10 do {this addItemToVest "RH_20Rnd_556x45_Red";};
this addBackpack "usm_pack_st138_prc77";
this addHeadgear "usm_bdu_cap_odg";
this addWeapon "RH_M16A1gl";
this addWeapon "CUP_hgun_Colt1911";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";