this forceAddUniform "skn_u_nbc_opf_yellow";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30Rnd_556x45_EPR_sg550";};
this addItemToVest "CUP_17Rnd_9x19_glock17";
for "_i" from 1 to 5 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 5 do {this addItemToVest "SmokeShellRed";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 8 do {this addItemToBackpack "CUP_1Rnd_StarCluster_White_M203";};
for "_i" from 1 to 8 do {this addItemToBackpack "CUP_1Rnd_StarCluster_Red_M203";};
for "_i" from 1 to 8 do {this addItemToBackpack "CUP_1Rnd_StarCluster_Green_M203";};
this addHeadgear "H_PASGT_basic_black_F";
this addGoggles "skn_m50_gas_mask_hood_wd";
this addWeapon "hlc_rifle_SG551SB_TAC_GL";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addPrimaryWeaponItem "CUP_optic_CompM2_low";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this addWeapon "Rangefinder";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";
