this forceAddUniform "skn_u_nbc_opf_yellow";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30Rnd_556x45_EPR_sg550";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_PASGT_basic_white_F";
this addGoggles "skn_m50_gas_mask_hood_wd";
this addWeapon "hlc_rifle_SG553SB_TAC";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addPrimaryWeaponItem "CUP_optic_CompM2_low";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";
