this forceAddUniform "CUP_U_B_CDF_FST_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_I_RACS_Carrier_Rig_wdl_2";
this addItemToVest "HandGrenade";
this addItemToVest "SmokeShell";
for "_i" from 1 to 2 do {this addItemToVest "Chemlight_green";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Green";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_15Rnd_9x19_B_P226";};
this addBackpack "B_FieldPack_oli";
this addHeadgear "CUP_H_SLA_Beret";
this addGoggles "G_Lady_Blue";
this addWeapon "hlc_rifle_ACR_mid_black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "hlc_pistol_P226R_Combat";
this addHandgunItem "acc_flashlight_pistol";
this addHandgunItem "HLC_optic_VTAC";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";