this forceAddUniform "CUP_U_O_SLA_Officer_Suit";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_I_RACS_Carrier_Rig_wdl_3";
this addItemToVest "HandGrenade";
this addItemToVest "SmokeShell";
for "_i" from 1 to 2 do {this addItemToVest "Chemlight_green";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_20Rnd_TE1_Green_Tracer_762x51_SCAR";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_15Rnd_9x19_B_P226";};
this addBackpack "B_FieldPack_oli";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_StarFlare_White_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_StarCluster_White_M203";};
this addItemToBackpack "CUP_FlareWhite_M203";
this addHeadgear "CUP_H_SLA_Beret";
this addGoggles "G_Lady_Blue";
this addWeapon "CUP_arifle_Mk17_CQC_EGLM_black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "hlc_pistol_P226R_Combat";
this addHandgunItem "acc_flashlight_pistol";
this addHandgunItem "HLC_optic_VTAC";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this addWeapon "Binocular";
