this forceAddUniform "MNP_CombatUniform_ASA_GC2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_TS_2";
for "_i" from 1 to 3 do {this addItemToVest "hlc_15Rnd_9x19_SD_P226";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_100Rnd_762x51_M_M60E4";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_100Rnd_762x51_M_M60E4";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
this addHeadgear "MNP_Helmet_PAGST_OD";
this addGoggles "G_Balaclava_blk";
this addWeapon "hlc_lmg_M60E4";
this addWeapon "hlc_pistol_P229R_Combat";
this addHandgunItem "hlc_muzzle_TiRant9S";
this addHandgunItem "HLC_optic228_HP";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";