this forceAddUniform "MNP_CombatUniform_ASA_GC2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_TS_2";
for "_i" from 1 to 3 do {this addItemToVest "hlc_15Rnd_9x19_SD_P226";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 9 do {this addItemToVest "hlc_30rnd_556x45_EPR_G36";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_HE_M203";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_HEDP_M203";};
this addHeadgear "MNP_Helmet_PAGST_OD";
this addGoggles "G_Balaclava_blk";
this addWeapon "hlc_rifle_G36VAG36";
this addPrimaryWeaponItem "CUP_optic_ZDDot";
this addWeapon "hlc_pistol_P229R_Combat";
this addHandgunItem "hlc_muzzle_TiRant9S";
this addHandgunItem "HLC_optic228_HP";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";