this forceAddUniform "MNP_CombatUniform_ASA_GC2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_TS_2";
for "_i" from 1 to 9 do {this addItemToVest "hlc_30rnd_556x45_EPR_G36";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_15Rnd_9x19_SD_P226";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addHeadgear "MNP_Helmet_PAGST_OD";
this addGoggles "G_Balaclava_blk";
this addBackpack "CUP_B_ACRPara_m95";
for "_i" from 1 to 50 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addWeapon "hlc_rifle_G36V";
this addPrimaryWeaponItem "CUP_optic_ZDDot";
this addWeapon "hlc_pistol_P229R_Combat";
this addHandgunItem "hlc_muzzle_TiRant9S";
this addHandgunItem "HLC_optic228_HP";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "rhs_1PN138";
