this forceAddUniform "CUP_U_O_RUS_VSR93_worn_gloves_MSV";
this addVest "CUP_V_RUS_6B3_1";
this removeItems "ACE_morphine";
this removeItems "ACE_fieldDressing";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";

for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_TE1_Yellow_Tracer_545x39_AK74M_M";};
this addBackpack "CUP_B_RUS_Pack_Medic";
clearAllItemsFromBackpack this;
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 6 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "CUP_H_RUS_6B27";
this addWeapon "CUP_arifle_AK74M";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";