this forceAddUniform "CFP_75th_CRYE_V4_Full";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_LBT6094_operator_Multicam";
for "_i" from 1 to 5 do {this addItemToVest "CUP_30Rnd_556x45_PMAG_QP";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_30Rnd_556x45_PMAG_QP_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_15Rnd_9x19_B_P226";};
this addBackpack "CFP_Kitbag_MCam_Grn";
for "_i" from 1 to 8 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "UGL_FlareRed_F";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeOrange_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokePurple_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "SmokeShellOrange";};
for "_i" from 1 to 3 do {this addItemToBackpack "SmokeShellPurple";};
for "_i" from 1 to 3 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 2 do {this addItemToBackpack "Laserbatteries";};
this addHeadgear "CFP_OpsC_Covered2";
this addGoggles "G_Bandanna_tan";
this addWeapon "CUP_arifle_mk18_m203_black";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P229R_Elite";
this addWeapon "Laserdesignator";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";