this forceAddUniform "CFP_75th_CRYE_V4_Full";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_LBT6094_operator_Multicam";
for "_i" from 1 to 5 do {this addItemToVest "CUP_30Rnd_556x45_PMAG_QP";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_30Rnd_556x45_PMAG_QP_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_15Rnd_9x19_B_P226";};
this addBackpack "CFP_Kitbag_MCam_Grn";
for "_i" from 1 to 25 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
this addHeadgear "CFP_OpsC_Covered2";
this addWeapon "CUP_arifle_mk18_black";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P229R_Elite";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
[this,"USP_PATCH_MORALE_MEDIC_CROSS_BLK_RED"] call BIS_fnc_setUnitInsignia;
