this forceAddUniform "CFP_75th_CRYE_V4_Full";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_LBT6094_operator_Multicam";
for "_i" from 1 to 4 do {this addItemToVest "CUP_30Rnd_556x45_PMAG_QP";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_30Rnd_556x45_PMAG_QP_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "HandGrenade";
for "_i" from 1 to 2 do {this addItemToVest "hlc_15Rnd_9x19_B_P226";};
this addBackpack "CFP_Carryall_Multicam";
this addItemToBackpack "CUP_SMAW_Spotting";
this addItemToBackpack "CUP_SMAW_HEAA_M";
this addHeadgear "CFP_OpsC_Covered2";
this addWeapon "CUP_arifle_mk18_black";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "CUP_launch_Mk153Mod0";
this addSecondaryWeaponItem "CUP_optic_SMAW_Scope";
this addWeapon "hlc_pistol_P229R_Elite";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";