this forceAddUniform "V_ARCunis_ARCTech_bduAOR2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_MX991";
this addVest "Avest2";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "hlc_200rnd_556x45_B_SAW";
this addBackpack "AOR2_Assault_Pack";
for "_i" from 1 to 4 do {this addItemToBackpack "SmokeShell";};
this addItemToBackpack "hlc_15Rnd_9x19_JHP_P226";
this addItemToBackpack "hlc_200rnd_556x45_B_SAW";
this addItemToBackpack "hlc_200rnd_556x45_T_SAW";
this addHeadgear "AOR2Helm1";
this addWeapon "hlc_lmg_mk46";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P226R";
this addHandgunItem "hlc_acc_TLR1";
this addHandgunItem "HLC_optic_Siglite";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen6";