this forceAddUniform "MNP_CombatUniform_NOR_D_B";
this addVest "CUP_V_B_Eagle_SPC_MG";
for "_i" from 1 to 2 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addBackpack "B_Carryall_cbr";
for "_i" from 1 to 5 do {this addItemToBackpack "hlc_50Rnd_762x51_M_MG3";};
this addItemToBackpack "hlc_250Rnd_762x51_T_MG3";
this addHeadgear "H_HelmetB_sand";
this addWeapon "hlc_lmg_MG3KWS_b";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this linkItem "ItemWatch";
