this forceAddUniform "MNP_CombatUniform_NOR_D_A";
this addVest "CUP_V_B_Eagle_SPC_Corpsman";
for "_i" from 1 to 2 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 6 do {this addItemToVest "hlc_20rnd_762x51_T_G3";};
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 8 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_20rnd_762x51_T_G3";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_20rnd_762x51_b_G3";};
this addHeadgear "H_HelmetB_sand";
this addWeapon "hlc_rifle_g3ka4";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this linkItem "ItemWatch";
