this forceAddUniform "MNP_CombatUniform_US3Co_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToUniform "hlc_30rnd_556x45_EPR";};
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "hlc_30rnd_556x45_EPR";
for "_i" from 1 to 2 do {this addItemToVest "hlc_30rnd_556x45_S";};
for "_i" from 1 to 4 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
this addBackpack "CUP_B_AssaultPack_Black";
this addItemToBackpack "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 3 do {this addItemToBackpack "UGL_FlareWhite_F";};
for "_i" from 1 to 2 do {this addItemToBackpack "UGL_FlareGreen_F";};
for "_i" from 1 to 2 do {this addItemToBackpack "UGL_FlareRed_F";};
this addHeadgear "CUP_H_USArmy_Helmet_Pro_gog";
this addWeapon "hlc_rifle_Colt727_GL";
this addPrimaryWeaponItem "hlc_muzzle_556NATO_M42000";
this addPrimaryWeaponItem "CUP_optic_CompM2_Black";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
