this forceAddUniform "MNP_CombatUniform_US3Co_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30rnd_556x45_S";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addBackpack "usm_pack_m5_medic";
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 8 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_salineIV_500";};
this addHeadgear "CUP_H_USArmy_Helmet_Pro";
this addWeapon "hlc_rifle_Colt727";
this addPrimaryWeaponItem "hlc_muzzle_556NATO_M42000";
this addPrimaryWeaponItem "CUP_optic_CompM2_Black";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";

