this forceAddUniform "MNP_CombatUniform_US3Co_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30rnd_556x45_S";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addHeadgear "CUP_H_USArmy_Helmet_Pro";
this addWeapon "hlc_rifle_Colt727";
this addPrimaryWeaponItem "hlc_muzzle_556NATO_M42000";
this addPrimaryWeaponItem "CUP_optic_CompM2_Black";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
