this forceAddUniform "usm_bdu_odg";
this addVest "usm_vest_LBE_mg";
for "_i" from 1 to 3 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToVest "ACE_HandFlare_Red";};
this addItemToVest "SmokeShell";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "ACE_HandFlare_Green";
this addBackpack "usm_pack_762x51_ammobelts";
this addItemToBackpack "ACE_Flashlight_XL50";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
this addItemToBackpack "hlc_100Rnd_762x51_M_M60E4";
this addHeadgear "CUP_H_USArmy_Helmet_M1_Olive";
this addWeapon "hlc_lmg_m60";
this addWeapon "CUP_hgun_Colt1911";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
