this forceAddUniform "CUP_U_B_BAF_DDPM_UBACSTSHIRTKNEE";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_HiRed";};
this addVest "CUP_V_B_BAF_DDPM_Osprey_Mk3_AutomaticRifleman";
for "_i" from 1 to 4 do {this addItemToVest "CUP_200Rnd_TE1_Red_Tracer_556x45_M249";};
this addHeadgear "CUP_H_BAF_DDPM_Mk6_EMPTY";
this addWeapon "LMG_03_F";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "optic_Holosight_smg_blk_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";