this forceAddUniform "U_B_CTRG_Soldier_3_F";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_CableTie";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACRE_PRC343";
this addItemToUniform "Chemlight_red";
this addVest "V_PlateCarrier1_tna_F";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 7 do {this addItemToVest "20Rnd_762x51_Mag";};
this addItemToVest "16Rnd_9x21_Mag";
this addBackpack "B_AssaultPack_dgtl";
this addHeadgear "H_HelmetB_Enh_tna_F";
this addWeapon "arifle_SPAR_03_khk_F";
this addPrimaryWeaponItem "muzzle_snds_B_khk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2";
this addPrimaryWeaponItem "optic_Aco";
this addPrimaryWeaponItem "bipod_01_F_khk";
this addWeapon "hgun_P07_khk_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";
this linkItem "ItemGPS";
this linkItem "NVGoggles";
