this forceAddUniform "MNP_CombatUniform_RU_Med";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "MNP_Vest_RU_T2";
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 3 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 6 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_545x39_t_ak";};
this addBackpack "B_ViperLightHarness_oli_F";
this addItemToBackpack "ToolKit";
this addHeadgear "CUP_H_SLA_TankerHelmet";
this addWeapon "hlc_rifle_aks74u";
this addWeapon "CUP_hgun_Makarov";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";