this forceAddUniform "CUP_U_C_Worker_03";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addVest "CUP_V_B_ALICE";
this addItemToVest "CUP_HandGrenade_RGD5";
this addItemToVest "hlc_100Rnd_792x57_M_MG42";
this addBackpack "CUP_B_AlicePack_Khaki";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_100Rnd_792x57_M_MG42";};
this addHeadgear "CUP_H_SLA_BeanieGreen";
this addWeapon "hlc_lmg_MG42";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
