this forceAddUniform "CUP_U_C_Mechanic_01";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "usm_vest_LBE_gr";
this addItemToVest "CUP_HandGrenade_RGD5";
for "_i" from 1 to 12 do {this addItemToVest "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_1Rnd_StarFlare_White_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_1Rnd_StarFlare_Red_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_1Rnd_StarFlare_Green_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_FlareGreen_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_FlareRed_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_FlareYellow_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_SmokeRed_M203";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_1Rnd_SmokeGreen_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_8Rnd_9x18_Makarov_M";};
this addBackpack "CUP_B_AlicePack_Khaki";
for "_i" from 1 to 4 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 4 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 4 do {this addItemToBackpack "SmokeShellPurple";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_HandFlare_Green";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_HandFlare_Red";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_HandFlare_Yellow";};
for "_i" from 1 to 20 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
this addHeadgear "CUP_H_C_Beanie_01";
this addWeapon "CUP_glaunch_M79";
this addWeapon "CUP_hgun_Makarov";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";