this forceAddUniform "CUP_O_TKI_Khet_Jeans_02";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
for "_i" from 1 to 3 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "CUP_V_B_ALICE";
this addItemToVest "CUP_HandGrenade_RGD5";
for "_i" from 1 to 9 do {this addItemToVest "CUP_10Rnd_762x39_SaigaMk03_M";};
this addBackpack "CUP_B_AlicePack_Khaki";
this addHeadgear "CUP_H_C_Beanie_02";
this addGoggles "G_Squares";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addWeapon "CUP_arifle_SAIGA_MK03";
this addWeapon "CUP_hgun_Makarov";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
