removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this forceAddUniform "U_B_HeliPilotCoveralls";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addVest "V_TacChestrig_grn_F";
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_9x21_Mag_SMG_02";};
this addHeadgear "H_PilotHelmetHeli_B";
this addWeapon "SMG_05_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
