this forceAddUniform "CUP_U_B_USMC_FROG4_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "CUP_V_B_Eagle_SPC_AR";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_MapTools";
this addItemToVest "ACE_EarPlugs";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToVest "150Rnd_556x45_Drum_Mag_Tracer_F";};
this addBackpack "B_AssaultPack_cbr";
this addItemToBackpack "ACE_EntrenchingTool";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToBackpack "150Rnd_556x45_Drum_Mag_Tracer_F";};
this addItemToBackpack "ACE_Chemlight_HiRed";
this addHeadgear "H_HelmetSpecB";
this addWeapon "arifle_SPAR_02_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Hamr";
this addPrimaryWeaponItem "bipod_01_F_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";
this linkItem "ItemGPS";
this linkItem "CUP_NVG_HMNVS";
