this forceAddUniform "CUP_U_B_USMC_FROG4_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 2 do {this addItemToUniform "11Rnd_45ACP_Mag";};
this addVest "CUP_V_B_Eagle_SPC_Officer";
this addItemToVest "ACE_MapTools";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_EarPlugs";
for "_i" from 1 to 3 do {this addItemToVest "11Rnd_45ACP_Mag";};
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "ACE_HandFlare_White";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_FlareWhite_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_FlareRed_M203";};
this addItemToBackpack "CUP_1Rnd_StarCluster_Red_M203";
this addItemToBackpack "CUP_1Rnd_StarCluster_White_M203";
this addItemToBackpack "CUP_1Rnd_StarCluster_Green_M203";
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
this addHeadgear "H_HelmetSpecB";
this addWeapon "arifle_SPAR_01_GL_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "hgun_Pistol_heavy_01_F";
this addHandgunItem "acc_flashlight_pistol";
this addWeapon "ACE_Vector";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "CUP_NVG_HMNVS";