this forceAddUniform "CUP_U_B_USMC_FROG1_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "CUP_V_B_Eagle_SPC_Crew";
this addItemToVest "ACE_EarPlugs";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_MapTools";
this addItemToVest "ACE_RangeTable_82mm";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "ACE_Chemlight_HiRed";
for "_i" from 1 to 4 do {this addItemToVest "11Rnd_45ACP_Mag";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 4 do {this addItemToBackpack "30Rnd_556x45_Stanag_red";};
this addHeadgear "H_HelmetSpecB";
this addWeapon "arifle_SPAR_01_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "hgun_Pistol_heavy_01_F";
this addHandgunItem "acc_flashlight_pistol";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "CUP_NVG_HMNVS";