this forceAddUniform "CUP_U_B_USMC_FROG3_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_MapTools";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 4 do {this addItemToUniform "11Rnd_45ACP_Mag";};
this addVest "CUP_V_B_Eagle_SPC_Crew";
this addItemToVest "ACE_Chemlight_HiRed";
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
this addBackpack "B_LegStrapBag_coyote_F";
this addHeadgear "CUP_H_USMC_Crew_Helmet";
this addWeapon "arifle_SPAR_01_blk_F";
this addPrimaryWeaponItem "acc_flashlight";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "hgun_Pistol_heavy_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "CUP_NVG_HMNVS";