this forceAddUniform "CUP_U_B_USMC_FROG1_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 4 do {this addItemToUniform "11Rnd_45ACP_Mag";};
this addVest "CUP_V_B_Eagle_SPC_DMR";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_Chemlight_HiRed";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 6 do {this addItemToVest "ACE_20Rnd_762x51_Mag_Tracer_Dim";};
for "_i" from 1 to 3 do {this addItemToVest "11Rnd_45ACP_Mag";};
this addHeadgear "H_HelmetSpecB_paint1";
this addWeapon "arifle_SPAR_03_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_MRCO";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "hgun_Pistol_heavy_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen7";