this forceAddUniform "CUP_U_B_USMC_FROG4_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "CUP_V_B_Eagle_SPC_GL";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_MapTools";
for "_i" from 1 to 9 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_FlareWhite_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_1Rnd_SmokeRed_M203";};
this addBackpack "B_AssaultPack_cbr";
this addItemToBackpack "ACE_EntrenchingTool";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
this addItemToBackpack "ACE_Chemlight_HiRed";
this addHeadgear "H_HelmetSpecB";
this addWeapon "arifle_SPAR_01_GL_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen7";