this forceAddUniform "CUP_U_B_USMC_FROG2_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "CUP_V_B_Eagle_SPC_Corpsman";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_IR_Strobe_Item";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
this addBackpack "usm_pack_m5_medic";
for "_i" from 1 to 25 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 7 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
this addHeadgear "H_HelmetSpecB";
this addWeapon "arifle_SPAR_01_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen7";
