this forceAddUniform "CUP_U_B_USMC_FROG4_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "CUP_V_B_Eagle_SPC_MG";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToVest "200Rnd_556x45_Box_Tracer_Red_F";};
this addBackpack "B_AssaultPack_cbr";
this addItemToBackpack "ACE_EntrenchingTool";
this addItemToBackpack "ACE_Chemlight_HiRed";
for "_i" from 1 to 2 do {this addItemToBackpack "200Rnd_556x45_Box_Tracer_Red_F";};
this addHeadgear "H_HelmetSpecB";
this addWeapon "LMG_03_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Hamr";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen7";