this forceAddUniform "CUP_U_B_USMC_FROG4_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "CUP_V_B_Eagle_SPC_Rifleman";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_Flashlight_XL50";
for "_i" from 1 to 9 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "ACE_Chemlight_HiRed";
this addBackpack "B_AssaultPack_cbr";
this addItemToBackpack "ACE_EntrenchingTool";
this addItemToBackpack "SmokeShell";
this addHeadgear "H_HelmetSpecB";
this addWeapon "arifle_SPAR_01_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight";
this addPrimaryWeaponItem "bipod_01_F_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen7";