this forceAddUniform "U_B_CombatUniform_mcam";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 2 do {this addItemToUniform "hlc_12Rnd_40SW_B_P226";};
this addVest "V_PlateCarrier2_rgr";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A1_HE";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_50Rnd_762x51_B_MG3";};
this addBackpack "B_FieldPack_oli";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_100Rnd_762x51_T_MG3";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_100Rnd_762x51_Barrier_MG3";};
this addHeadgear "H_HelmetSpecB_paint1";
this addWeapon "hlc_lmg_MG3_optic";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "hlc_pistol_P226R_40Elite";
this addHandgunItem "HLC_optic_HP";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
