this forceAddUniform "U_B_CombatUniform_mcam";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addVest "V_PlateCarrier2_rgr";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30Rnd_556x45_EPR_sg550";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_556x45_T_sg550";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A1_HE";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_12Rnd_40SW_B_P226";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
this addHeadgear "H_HelmetSpecB_paint1";
this addWeapon "hlc_rifle_SG553LB_TAC";
this addPrimaryWeaponItem "optic_ACO_grn";
this addWeapon "hlc_pistol_P226R_40Elite";
this addHandgunItem "HLC_optic_HP";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
