this forceAddUniform "CUP_I_B_PMC_Unit_19";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_PMC_CIRAS_Black_Veh";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 3 do {this addItemToVest "29rnd_300BLK_STANAG";};
for "_i" from 1 to 2 do {this addItemToVest "29rnd_300BLK_STANAG_T";};
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addBackpack "CUP_B_USPack_Black";
for "_i" from 1 to 25 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_salineIV";};
this addHeadgear "CUP_H_PMC_Cap_Back_PRR_Grey";
this addWeapon "hlc_rifle_honeybadger";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
