this forceAddUniform "CUP_I_B_PMC_Unit_15";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_PMC_CIRAS_Black_TL";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 5 do {this addItemToVest "29rnd_300BLK_STANAG";};
this addHeadgear "CUP_H_PMC_Cap_Back_PRR_Tan";
this addWeapon "hlc_rifle_bcmblackjack";
this addPrimaryWeaponItem "CUP_optic_CompM2_Black";
this addWeapon "CUP_launch_M136";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
