this forceAddUniform "CUP_I_B_PMC_Unit_11";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_epinephrine";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_personalAidKit";
this addVest "CUP_V_PMC_CIRAS_Black_TL";
this addItemToVest "hlc_12Rnd_357SIG_B_P226";
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag";};
this addHeadgear "H_HelmetB_light_black";
this addWeapon "CUP_arifle_Mk16_CQC_FG_black";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "hlc_pistol_P226R_Stainless";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
