this forceAddUniform "usm_bdu_w";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "usm_vest_rba_lbv_rmp";
for "_i" from 1 to 4 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 4 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_7Rnd_45ACP_1911";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 6 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addBackpack "usm_pack_200rnd_556_bandoliers";
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
this addHeadgear "usm_helmet_pasgt_g_w";
this addWeapon "RH_M16A2gl";
this addWeapon "CUP_hgun_Colt1911";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
