this forceAddUniform "CUP_U_B_USMC_FROG4_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "30Rnd_556x45_Stanag";};
this addVest "CUP_V_B_Eagle_SPC_Rifleman";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_MapTools";
this addItemToVest "ACE_EarPlugs";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 8 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addBackpack "B_Kitbag_cbr";
this addItemToBackpack "ACE_EntrenchingTool";
this addItemToBackpack "ACE_wirecutter";
this addItemToBackpack "ACE_Chemlight_HiRed";
for "_i" from 1 to 6 do {this addItemToBackpack "150Rnd_556x45_Drum_Mag_Tracer_F";};
this addHeadgear "H_HelmetSpecB_snakeskin";
this addWeapon "arifle_SPAR_01_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "ACE_Vector";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen7";