this forceAddUniform "CUP_U_B_USMC_FROG1_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_SpottingScope";
this addVest "CUP_V_B_Eagle_SPC_Scout";
this addItemToVest "ACE_EarPlugs";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_MapTools";
this addItemToVest "ACE_Chemlight_HiRed";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
this addItemToVest "30Rnd_556x45_Stanag";
this addHeadgear "H_HelmetSpecB_paint1";
this addWeapon "arifle_SPAR_01_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "ACE_Vector";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen7";