this forceAddUniform "CUP_U_B_USMC_FROG3_WMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "Laserbatteries";
this addVest "CUP_V_B_Eagle_SPC_RTO";
this addItemToVest "ACE_MapTools";
this addItemToVest "ACE_Flashlight_XL50";
this addItemToVest "ACE_IR_Strobe_Item";
this addItemToVest "ACE_EarPlugs";
for "_i" from 1 to 9 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 8 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_FlareRed_M203";};
for "_i" from 1 to 6 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_Chemlight_HiYellow";};
this addItemToBackpack "SmokeShellPurple";
this addItemToBackpack "SmokeShellBlue";
this addItemToBackpack "SmokeShellOrange";
this addItemToBackpack "SmokeShellYellow";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_HEDP_M203";};
this addHeadgear "H_HelmetB_light_sand";
this addWeapon "arifle_SPAR_01_GL_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "Laserdesignator";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen7";