this forceAddUniform "usm_bdu_w";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "16Rnd_9x21_Mag";
this addVest "V_PlateCarrier1_blk";
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_Green";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "CUP_H_RUS_6B27_olive";
this addGoggles "G_Balaclava_oli";
this addWeapon "hlc_rifle_ak12";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_Duty";
this addHandgunItem "CUP_acc_CZ_M3X";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
