this addWeapon "hlc_rifle_ak74m_gl";
this addPrimaryWeaponItem "hlc_30Rnd_545x39_B_AK";
this forceAddUniform "CUP_U_I_GUE_Flecktarn2";
this addVest "V_Chestrig_rgr";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_epinephrine";
for "_i" from 1 to 2 do {this addItemToUniform "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 6 do {this addItemToVest "hlc_30Rnd_545x39_t_ak";};
this addItemToVest "hlc_30Rnd_545x39_B_AK";
this addItemToVest "hlc_VOG25_AK";
this addItemToVest "SmokeShell";
this addHeadgear "H_Cap_oli";
this addGoggles "G_Bandanna_beast";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";