this addWeapon "hlc_rifle_ak74";
this addPrimaryWeaponItem "hlc_30Rnd_545x39_t_ak";
this forceAddUniform "CUP_U_I_GUE_Flecktarn2";
this addVest "V_Chestrig_rgr";
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_epinephrine";
for "_i" from 1 to 7 do {this addItemToVest "hlc_30Rnd_545x39_t_ak";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 6 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_tourniquet";};
this addHeadgear "H_Cap_oli";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";