this forceAddUniform "U_I_Wetsuit";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_RebreatherIA";
this addBackpack "CUP_B_USMC_MOLLE_WDL";
this addItemToBackpack "ACRE_PRC117F";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_15Rnd_9x19_SD_P226";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_HandFlare_White";};
this addItemToBackpack "ACE_M84";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_200rnd_556x45_T_SAW";};
this addWeapon "CUP_lmg_m249_pip4";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "hlc_pistol_P229R_Combat";
this addHandgunItem "hlc_muzzle_TiRant9S";
this addHandgunItem "acc_flashlight_pistol";
this addHandgunItem "HLC_optic228_VTAC";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ACE_Altimeter";

this addGoggles "G_I_Diving";
