this forceAddUniform "U_I_Wetsuit";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_RebreatherIA";
this addBackpack "CUP_B_USMC_MOLLE_WDL";
this addItemToBackpack "ACRE_PRC117F";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_15Rnd_9x19_SD_P226";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_HandFlare_White";};
this addItemToBackpack "ACE_M84";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 6 do {this addItemToBackpack "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "UGL_FlareWhite_F";};
this addWeapon "CUP_arifle_M4A1_BUIS_camo_GL";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "hlc_pistol_P229R_Combat";
this addHandgunItem "hlc_muzzle_TiRant9S";
this addHandgunItem "acc_flashlight_pistol";
this addHandgunItem "HLC_optic228_VTAC";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ACE_Altimeter";
this linkItem "ACE_NVG_Gen1";
this addGoggles "G_I_Diving";