this forceAddUniform "U_I_Wetsuit";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "V_RebreatherIA";
this addBackpack "CUP_B_USMC_AssaultPack";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_15Rnd_9x19_SD_P226";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_HandFlare_White";};
this addItemToBackpack "ACE_M84";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 6 do {this addItemToBackpack "30Rnd_556x45_Stanag_Tracer_Red";};
this addWeapon "hlc_rifle_M4a1carryhandle";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "hlc_pistol_P229R_Combat";
this addHandgunItem "hlc_muzzle_TiRant9S";
this addHandgunItem "acc_flashlight_pistol";
this addHandgunItem "HLC_optic228_VTAC";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ACE_Altimeter";

this addGoggles "G_I_Diving";
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};

