this forceAddUniform "U_I_Wetsuit";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "V_RebreatherIA";
this addBackpack "CUP_B_USMC_MOLLE_WDL";
this addItemToBackpack "ACE_Clacker";
for "_i" from 1 to 5 do {this addItemToBackpack "DemoCharge_Remote_Mag";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_15Rnd_9x19_SD_P226";};
for "_i" from 1 to 2 do {this addItemToBackpack "B_IR_Grenade";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_Chemlight_IR";};
this addItemToBackpack "ACE_M84";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_30rnd_556x45_MDim";};
this addWeapon "hlc_rifle_M4a1carryhandle";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2";
this addWeapon "hlc_pistol_P229R_Combat";
this addHandgunItem "hlc_muzzle_TiRant9S";
this addHandgunItem "acc_flashlight_pistol";
this addHandgunItem "HLC_optic228_VTAC";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ACE_Altimeter";
this linkItem "ACE_NVG_Gen1";
this addGoggles "G_I_Diving";