this forceAddUniform "CUP_U_I_GUE_Flecktarn3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "usm_vest_rba";
for "_i" from 1 to 2 do {this addItemToVest "CUP_18Rnd_9x19_Phantom";};
this addBackpack "CUP_B_RUS_Backpack";
this addItemToBackpack "SmokeShell";
this addItemToBackpack "HandGrenade";
for "_i" from 1 to 7 do {this addItemToBackpack "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_30Rnd_762x39_t_ak";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_VOG25_AK";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_GRD_White";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_GRD_Red";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_GRD_green";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_IlumFlareWhite_GP25_M";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_IlumFlareRed_GP25_M";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_IlumFlareGreen_GP25_M";};
this addGoggles "G_Bandanna_beast";
this addWeapon "hlc_rifle_akmgl";
this addWeapon "CUP_hgun_Phantom";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";