this forceAddUniform "CUP_U_I_GUE_Flecktarn3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "usm_vest_rba_lbe_gr";
this addItemToVest "SmokeShell";
this addItemToVest "HandGrenade";
for "_i" from 1 to 7 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_1Rnd_SmokeGreen_GP25_M";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_1Rnd_SmokeRed_GP25_M";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_762x39_t_ak";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_1Rnd_HE_GP25_M";};
this addBackpack "B_Mortar_01_weapon_F";
this addGoggles "G_Bandanna_tan";
this addWeapon "hlc_rifle_akmgl";
this addWeapon "CUP_hgun_Phantom";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";