this forceAddUniform "CFP_U_BattleDressUniform_ana_wddark";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_ITV_Grenadier_Green";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A1_HE";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 9 do {this addItemToVest "CUP_30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 6 do {this addItemToVest "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addHeadgear "CFP_Basic_Helmet_Black";
this addWeapon "CUP_arifle_M16A4_GL";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
