this forceAddUniform "CFP_U_FieldUniform_ana_spec4cewd_light";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_ITV_Grenadier_Green";
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_TE1_Red_Tracer_545x39_AK_M";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A1_HE";};
this addItemToVest "SmokeShell";
this addBackpack "CFP_RPGPack_Khaki";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_PG7VL_M";};
this addHeadgear "CFP_Basic_Helmet_Tan";
this addWeapon "CUP_arifle_AK74";
this addWeapon "CUP_launch_RPG7V";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";