this forceAddUniform "CUP_U_I_GUE_Flecktarn2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addVest "CUP_V_CDF_CrewBelt";
for "_i" from 1 to 6 do {this addItemToVest "16Rnd_9x21_Mag";};
this addBackpack "CUP_B_USMC_AssaultPack";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addGoggles "G_Balaclava_blk";
this addWeapon "CUP_hgun_Duty";
this addHandgunItem "muzzle_snds_L";
this addHandgunItem "CUP_acc_CZ_M3X";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemMap";