this forceAddUniform "CUP_U_I_GUE_Flecktarn2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addVest "CUP_V_CDF_CrewBelt";
for "_i" from 1 to 6 do {this addItemToVest "16Rnd_9x21_Mag";};
this addGoggles "G_Balaclava_blk";
this addWeapon "CUP_hgun_Duty";
this addHandgunItem "muzzle_snds_L";
this addHandgunItem "CUP_acc_CZ_M3X";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemMap";