this addWeapon "CUP_arifle_AK74";
this addPrimaryWeaponItem "CUP_acc_Flashlight_desert";
this addPrimaryWeaponItem "CUP_optic_Kobra";
this addPrimaryWeaponItem "CUP_30Rnd_TE1_Red_Tracer_545x39_AK74_plum_M";
this addWeapon "hgun_Rook40_F";
this addHandgunItem "16Rnd_9x21_Mag";
this forceAddUniform "MNP_CombatUniform_Militia_DB";
this addVest "MNP_Vest_NZ_1";
this addBackpack "B_Carryall_cbr";
this addWeapon "Binocular";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACE_Fortify";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 9 do {this addItemToVest "CUP_30Rnd_TE1_Red_Tracer_545x39_AK74_plum_M";};
for "_i" from 1 to 3 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 50 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_Banana";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 8 do {this addItemToBackpack "SmokeShell";};
this addHeadgear "SP_SSh68CoverHelmet_Tan1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";BIS_fnc_setUnitInsignia;
