this addWeapon "CUP_arifle_AK74";
this addPrimaryWeaponItem "CUP_acc_Flashlight_desert";
this addPrimaryWeaponItem "CUP_optic_Kobra";
this addPrimaryWeaponItem "CUP_30Rnd_TE1_Red_Tracer_545x39_AK74_plum_M";
this addWeapon "hgun_Rook40_F";
this addHandgunItem "16Rnd_9x21_Mag";
this forceAddUniform "MNP_CombatUniform_Militia_DB";
this addVest "MNP_Vest_NZ_2";
this addBackpack "B_Carryall_cbr";
this addWeapon "Binocular";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACE_Fortify";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 9 do {this addItemToVest "CUP_30Rnd_TE1_Red_Tracer_545x39_AK74_plum_M";};
for "_i" from 1 to 3 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_PG7VL_M";};
this addItemToBackpack "CUP_PG7VR_M";
this addHeadgear "SP_SSh68CoverHelmet_Tan1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";