this addWeapon "CUP_lmg_Pecheneg";
this addPrimaryWeaponItem "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M";
this addWeapon "hgun_Rook40_F";
this addHandgunItem "16Rnd_9x21_Mag";
this forceAddUniform "MNP_CombatUniform_Militia_DB";
this addVest "MNP_Vest_NZ_1";
this addBackpack "B_Carryall_cbr";
this addWeapon "Binocular";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACE_Fortify";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "16Rnd_9x21_Mag";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToVest "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M";
for "_i" from 1 to 2 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M";};
this addHeadgear "SP_SSh68CoverHelmet_Tan1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";