this forceAddUniform "CUP_U_B_USMC_PilotOverall";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACRE_PRC343";
this addVest "CUP_V_B_PilotVest";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30Rnd_9x19_B_MP5";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_15Rnd_9x19_M9";};
this addItemToVest "ACE_HandFlare_Green";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_AssaultPack_cbr";
this addItemToBackpack "ToolKit";
this addHeadgear "CUP_H_USMC_Helmet_Pilot";
this addGoggles "G_Aviator";
this addWeapon "hlc_smg_MP5N";
this addWeapon "CUP_hgun_M9";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";
