this forceAddUniform "CUP_U_B_USMC_FROG3_DMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 4 do {this addItemToUniform "Laserbatteries";};
this addVest "CUP_V_B_Eagle_SPC_RTO";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 8 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addItemToVest "CUP_15Rnd_9x19_M9";
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_FlareGreen_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_FlareRed_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "UGL_FlareCIR_F";};
for "_i" from 1 to 8 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_SmokeYellow_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_SmokePurple_Grenade_shell";};
this addHeadgear "CUP_H_USMC_LWH_NVGMOUNT_ESS_HS_DES";
this addGoggles "G_Sport_Red";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_M9";
this addWeapon "Laserdesignator";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "B_UavTerminal";