this forceAddUniform "U_I_G_Story_Protagonist_F";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addVest "V_Chestrig_blk";
this addItemToVest "rhs_mag_m67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 2 do {this addItemToVest "rhs_200rnd_556x45_M_SAW";};
this addHeadgear "rhsusf_opscore_bk_pelt";
this addWeapon "rhs_weap_m249";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";