this forceAddUniform "U_I_G_Story_Protagonist_F";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addVest "V_Chestrig_blk";
this addItemToVest "rhs_mag_m67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 5 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag";};
this addBackpack "B_TacticalPack_blk";
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_fieldDressing";};
this addItemToBackpack "ACE_epinephrine";
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV";};
this addHeadgear "rhsusf_opscore_bk_pelt";
this addWeapon "rhs_weap_hk416d10";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
