this forceAddUniform "CUP_U_B_BAF_MTP_UBACSLONGKNEE";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_HiRed";};
this addVest "CUP_V_B_BAF_DDPM_Osprey_Mk3_Rifleman";
for "_i" from 1 to 9 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
this addBackpack "CUP_B_Motherlode_Radio_MTP";
this addItemToBackpack "ToolKit";
this addHeadgear "CUP_H_BAF_DDPM_Mk6_EMPTY";
this addWeapon "CUP_arifle_L85A2_G";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "optic_yorris";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";