this forceAddUniform "MNP_CombatUniform_Scorpion_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_Fortify";
this addVest "MNP_Vest_Scorpion_1";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 3 do {this addItemToVest "16Rnd_9x21_Mag";};
this addItemToVest "hlc_200rnd_556x45_M_SAW";
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200rnd_556x45_M_SAW";};
this addHeadgear "MNP_Helmet_Scorpion";
this addWeapon "hlc_lmg_minimi_railed";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "CUP_hgun_Duty";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";