this forceAddUniform "MNP_CombatUniform_Scorpion_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_Fortify";
this addVest "MNP_Vest_Scorpion_1";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 3 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_100Rnd_762x51_T_M60E4";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
this addHeadgear "MNP_Helmet_Scorpion";
this addWeapon "hlc_lmg_mk48";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "CUP_hgun_Duty";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";