this forceAddUniform "MNP_CombatUniform_Scorpion_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_Fortify";
this addVest "MNP_Vest_Scorpion_1";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 3 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 7 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30rnd_556x45_M";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_100Rnd_762x51_T_M60E4";};
this addHeadgear "MNP_Helmet_Scorpion";
this addGoggles "G_Bandanna_oli";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "CUP_hgun_Duty";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";