comment "Exported from Arsenal by shredcov";
this forceAddUniform "MNP_CombatUniform_Germany_S";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_Germany";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "hlc_250Rnd_762x51_B_MG3";
this addBackpack "CUP_B_GER_Pack_Flecktarn";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_250Rnd_762x51_M_MG3";};
this addHeadgear "MNP_Helmet_Germany";
this addWeapon "hlc_lmg_MG3KWS_b";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
