comment "Exported from Arsenal by shredcov";
this forceAddUniform "CUP_U_B_GER_Flecktarn_2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToUniform "hlc_30Rnd_9x19_B_MP5";};
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
this addHeadgear "CUP_H_BAF_Helmet_Pilot";
this addWeapon "hlc_smg_MP5N";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
