comment "Exported from Arsenal by shredcov";
this forceAddUniform "MNP_CombatUniform_Germany";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_Germany_2";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "hlc_30rnd_556x45_EPR_G36";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30rnd_556x45_Tracers_G36";};
this addHeadgear "MNP_Helmet_Germany";
this addWeapon "hlc_rifle_G36A1";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
