this forceAddUniform "skn_u_nbc_bluf_mtp";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "usm_vest_rba_lbv_mg";
for "_i" from 1 to 8 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_FlareRed_M203";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addHeadgear "CUP_H_RACS_Helmet_olive";
this addGoggles "skn_m04_gas_mask_gre";
this addWeapon "CUP_arifle_Mk16_STD_EGLM_black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemGPS";

