this forceAddUniform "CUP_U_B_USMC_MARPAT_WDL_TwoKneepads";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_17Rnd_9x19_glock17";};
this addVest "CUP_V_I_RACS_Carrier_Rig_wdl_3";
this addItemToVest "HandGrenade";
this addItemToVest "SmokeShell";
for "_i" from 1 to 2 do {this addItemToVest "Chemlight_blue";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellBlue";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_20Rnd_TE1_Red_Tracer_762x51_SCAR";};
this addBackpack "B_FieldPack_oli";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_StarFlare_White_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_StarCluster_White_M203";};
this addItemToBackpack "CUP_FlareWhite_M203";
this addHeadgear "CUP_H_USMC_BOONIE_PRR_WDL";
this addGoggles "G_Sport_Red";
this addWeapon "CUP_arifle_Mk17_CQC_EGLM_black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_Glock17";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this addWeapon "Binocular";
