this forceAddUniform "usm_bdu_w";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "usm_vest_rba_lbe_mg";
for "_i" from 1 to 3 do {this addItemToVest "SmokeShell";};
this addItemToVest "MiniGrenade";
for "_i" from 1 to 3 do {this addItemToVest "CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M";};
this addHeadgear "usm_helmet_pasgt_g_w_m";
this addWeapon "CUP_lmg_M240";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
