this forceAddUniform "MNP_CombatUniform_DS_B";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "HandGrenade";};
this addVest "MNP_Vest_DS_1";
for "_i" from 1 to 3 do {this addItemToVest "CUP_15Rnd_9x19_M9";};
for "_i" from 1 to 9 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addBackpack "B_FieldPack_khk";
for "_i" from 1 to 3 do {this addItemToBackpack "MRAWS_HEAT_F";};
this addHeadgear "CUP_H_USMC_MICH2000_DEF_ESS_WDL";
this addWeapon "hlc_rifle_M4";
this addPrimaryWeaponItem "CUP_optic_CompM2_Black";
this addWeapon "launch_MRAWS_olive_rail_F";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";