this forceAddUniform "usm_bdu_w_m";
this addVest "usm_vest_lbv_mg_m";
for "_i" from 1 to 3 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 3 do {this addItemToVest "CUP_7Rnd_45ACP_1911";};
this addBackpack "CUP_B_AlicePack_Khaki";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200rnd_556x45_M_SAW";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200rnd_556x45_T_SAW";};
this addHeadgear "usm_helmet_pasgt_w_m";
this addWeapon "hlc_lmg_minimipara_long";
this addWeapon "CUP_hgun_Colt1911";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
