this forceAddUniform "usm_bdu_w_m";
this addVest "usm_vest_lbv_gr_m";
for "_i" from 1 to 3 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 3 do {this addItemToVest "CUP_7Rnd_45ACP_1911";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addBackpack "CUP_B_CivPack_WDL";
for "_i" from 1 to 7 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 6 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "usm_helmet_pasgt_w_m";
this addWeapon "RH_M16A2gl";
this addWeapon "CUP_hgun_Colt1911";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
