this forceAddUniform "usm_bdu_w_m";
this addVest "usm_vest_lbv_rm";
for "_i" from 1 to 3 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag_red";};
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 3 do {this addItemToVest "CUP_7Rnd_45ACP_1911";};
this addBackpack "CUP_B_AlicePack_Khaki";
this addHeadgear "usm_helmet_pasgt_w";
this addWeapon "RH_M16A2";
this addWeapon "CUP_hgun_Colt1911";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
