this forceAddUniform "U_I_CombatUniform";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "9Rnd_45ACP_Mag";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_MapTools";
this addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_HiRed";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_HiGreen";};
this addVest "V_PlateCarrierIAGL_dgtl";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Yellow";};
for "_i" from 1 to 4 do {this addItemToVest "UGL_FlareRed_F";};
this addBackpack "B_TacticalPack_oli";
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 6 do {this addItemToBackpack "ACE_HandFlare_Green";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_HandFlare_Red";};
this addItemToBackpack "SmokeShellRed";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShellGreen";};
this addItemToBackpack "SmokeShellBlue";
for "_i" from 1 to 6 do {this addItemToBackpack "UGL_FlareRed_F";};
for "_i" from 1 to 4 do {this addItemToBackpack "UGL_FlareGreen_F";};
for "_i" from 1 to 2 do {this addItemToBackpack "UGL_FlareYellow_F";};
for "_i" from 1 to 6 do {this addItemToBackpack "I_IR_Grenade";};
this addHeadgear "H_HelmetIA";
this addWeapon "arifle_Mk20_GL_F";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_ACO_grn";
this addWeapon "hgun_ACPC2_F";
this addWeapon "Laserdesignator_03";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";