this forceAddUniform "CUP_U_I_UNO_FST_1";
this addVest "CUP_V_CDF_6B3_2_Green";
this addItemToVest "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToVest "10Rnd_9x21_Mag";};
this addItemToVest "SmokeShell";
this addHeadgear "CUP_H_CDF_Beret_UN";
this addWeapon "hgun_Pistol_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
