this forceAddUniform "U_O_OfficerUniform_ocamo";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "9Rnd_45ACP_Mag";
this addVest "V_PlateCarrier2_blk";
for "_i" from 1 to 10 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_Carryall_khk";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_HelmetB_black";
this addGoggles "G_Bandanna_blk";
this addWeapon "arifle_Katiba_C_F";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "hgun_ACPC2_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
