this forceAddUniform "U_O_OfficerUniform_ocamo";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "9Rnd_45ACP_Mag";
this addVest "V_PlateCarrier2_blk";
for "_i" from 1 to 10 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addHeadgear "H_HelmetB_black";
this addGoggles "G_Bandanna_blk";
this addWeapon "arifle_Katiba_F";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "hgun_ACPC2_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
