this forceAddUniform "rhs_uniform_FROG01_wd";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_tourniquet";
this addVest "rhsusf_spc_squadleader";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag";};
for "_i" from 1 to 5 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red";};
this addBackpack "rhsusf_assault_eagleaiii_coy";
for "_i" from 1 to 5 do {this addItemToBackpack "rhs_mag_m715_Green";};
for "_i" from 1 to 6 do {this addItemToBackpack "rhs_mag_m713_Red";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_m661_green";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_m662_red";};
this addHeadgear "rhsusf_mich_bare_alt_tan";
this addWeapon "rhs_weap_m16a4_carryhandle_M203";
this addPrimaryWeaponItem "rhsusf_acc_eotech_552";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
