this forceAddUniform "rhs_uniform_FROG01_wd";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_EarPlugs";
this addVest "rhsusf_spc_rifleman";
for "_i" from 1 to 7 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 8 do {this addItemToBackpack "ACE_bodyBag";};
this addHeadgear "rhsusf_lwh_helmet_marpatwd_headset";
this addWeapon "rhs_weap_m4a1_carryhandle";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
