this forceAddUniform "rhs_uniform_FROG01_wd";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "rhs_m136_mag";
this addVest "rhsusf_spc_rifleman";
for "_i" from 1 to 7 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red";};
this addHeadgear "rhsusf_lwh_helmet_marpatwd_headset";
this addWeapon "rhs_weap_m4a1_carryhandle";
this addWeapon "rhs_weap_M136";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
