this forceAddUniform "rhs_uniform_FROG01_wd";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhsusf_spc";
for "_i" from 1 to 4 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red";};
this addBackpack "B_AssaultPack_blk";
this addItemToBackpack "ToolKit";
this addHeadgear "rhsusf_cvc_green_ess";
this addWeapon "rhs_weap_m4a1_carryhandle";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
