this forceAddUniform "U_I_HeliPilotCoveralls";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_MapTools";
this addVest "V_BandollierB_cbr";
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_9x21_Mag";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "CUP_HandGrenade_M67";
this addHeadgear "H_PilotHelmetHeli_I";
this addWeapon "hgun_PDW2000_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
