this forceAddUniform "U_I_CombatUniform_shortsleeve";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "9Rnd_45ACP_Mag";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addVest "V_PlateCarrierIAGL_dgtl";
this addItemToVest "SmokeShellGreen";
this addItemToVest "HandGrenade";
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Yellow";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_TacticalPack_oli";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 4 do {this addItemToBackpack "SmokeShell";};
this addHeadgear "H_HelmetIA_camo";
this addGoggles "G_Bandanna_blk";
this addWeapon "arifle_Mk20_F";
this addPrimaryWeaponItem "optic_ACO_grn";
this addWeapon "hgun_ACPC2_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
