this forceAddUniform "U_I_CombatUniform";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_PlateCarrierIA2_dgtl";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 3 do {this addItemToVest "9Rnd_45ACP_Mag";};
this addBackpack "B_TacticalPack_oli";
for "_i" from 1 to 3 do {this addItemToBackpack "150Rnd_93x64_Mag";};
this addHeadgear "H_HelmetIA";
this addGoggles "CUP_TK_NeckScarf";
this addWeapon "MMG_01_tan_F";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "hgun_ACPC2_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
