this forceAddUniform "U_I_CombatUniform";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "9Rnd_45ACP_Mag";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_PlateCarrierIAGL_dgtl";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Yellow";};
this addHeadgear "H_HelmetIA";
this addGoggles "G_Bandanna_blk";
this addWeapon "arifle_Mk20_F";
this addPrimaryWeaponItem "optic_ACO_grn";
this addWeapon "launch_NLAW_F";
this addWeapon "hgun_ACPC2_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
