this forceAddUniform "CUP_U_B_USMC_PilotOverall";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_PilotVest";
this addItemToVest "ACE_MapTools";
this addItemToVest "CUP_15Rnd_9x19_M9";
this addHeadgear "H_PilotHelmetHeli_B";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";
