this forceAddUniform "CUP_U_B_USMC_FROG4_DMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_30Rnd_556x45_Stanag";};
this addVest "CUP_V_B_Eagle_SPC_SL";
for "_i" from 1 to 6 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_HE_M203";};
this addItemToVest "SmokeShell";
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addItemToVest "CUP_FlareWhite_M203";
this addBackpack "CUP_B_AssaultPack_Coyote";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_1Rnd_Smoke_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_StarCluster_Green_M203";};
this addItemToBackpack "UGL_FlareRed_F";
this addHeadgear "CUP_H_USMC_MICH2000_DEF_DES";
this addWeapon "CUP_arifle_M16A4_GL";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
