this forceAddUniform "CUP_U_B_USMC_FROG4_DMARPAT";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_30Rnd_556x45_Stanag";};
this addVest "CUP_V_B_Eagle_SPC_SL";
for "_i" from 1 to 6 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addBackpack "CUP_B_USPack_Coyote";
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_StarCluster_Green_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 4 do {this addItemToBackpack "SmokeShellRed";};
this addHeadgear "CUP_H_USMC_MICH2000_DEF_DES";
this addWeapon "CUP_arifle_M16A4_GL";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "CUP_SOFLAM";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
