this forceAddUniform "CUP_U_B_FR_Corpsman";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_BandollierB_oli";
for "_i" from 1 to 6 do {this addItemToVest "CUP_17Rnd_9x19_glock17";};
this addBackpack "CUP_B_USMC_AssaultPack";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_tourniquet";};
this addItemToVest "ACE_M84";
this addHeadgear "CUP_H_CZ_Helmet09";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "muzzle_snds_L";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";