this forceAddUniform "CUP_U_B_USMC_PilotOverall";
this addItemToUniform "ACE_fieldDressing";
this addItemToUniform "ACE_packingBandage";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_PilotVest";
for "_i" from 1 to 6 do {this addItemToVest "CUP_18Rnd_9x19_Phantom";};
this addHeadgear "CUP_H_USMC_Helmet_Pilot";
this addWeapon "CUP_hgun_Phantom";
this addHandgunItem "muzzle_snds_L";
this addHandgunItem "CUP_acc_CZ_M3X";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";