removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this forceAddUniform "CUP_U_B_BAF_MTP_S1_RolledUp";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_17Rnd_9x19_glock17";};
this addItemToUniform "hlc_30Rnd_9x19_B_MP5";
this addVest "CUP_V_BAF_Osprey_Mk4_MTP_Rifleman";
this addItemToVest "CUP_HandGrenade_L109A2_HE";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30Rnd_9x19_B_MP5";};
this addBackpack "CUP_B_Bergen_BAF";
this addItemToBackpack "ToolKit";
this addHeadgear "CUP_H_BAF_Crew_Helmet_MTP";
this addWeapon "hlc_smg_MP5N";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
