this forceAddUniform "CFP_U_Crye_Multicam2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CFP_FAPC_Operator_Multicam";
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
this addBackpack "CFP_AssaultPack_Multicam";
for "_i" from 1 to 2 do {this addItemTobackpack "CUP_200Rnd_TE4_Yellow_Tracer_556x45_M249";};
this addItemToBackpack "ACE_EntrenchingTool";
this addHeadgear "CFP_OpsC_Uncov_Full";
this addWeapon "hlc_rifle_ACR_Carb_tan";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Flashlight_Tan_L";
this addPrimaryWeaponItem "CUP_optic_Eotech533";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this addWeapon "Binocular";