this forceAddUniform "CUP_U_I_GUE_Flecktarn3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_Fortify";
this addVest "usm_vest_rba";
this addBackpack "CUP_B_RUS_Backpack";
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
this addItemToBackpack "SmokeShell";
this addItemToBackpack "HandGrenade";
for "_i" from 1 to 5 do {this addItemToBackpack "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_30Rnd_545x39_t_ak";};
this addGoggles "G_Balaclava_oli";
this addWeapon "hlc_rifle_ak74";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";