this forceAddUniform "CUP_U_I_GUE_Flecktarn3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_Fortify";
this addVest "usm_vest_rba";
for "_i" from 1 to 2 do {this addItemToVest "CUP_18Rnd_9x19_Phantom";};
this addBackpack "CUP_B_RUS_Backpack";
this addItemToBackpack "SmokeShell";
this addItemToBackpack "HandGrenade";
for "_i" from 1 to 5 do {this addItemToBackpack "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_30Rnd_545x39_t_ak";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_FlareGreen_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_FlareRed_GP25_M";};
this addGoggles "G_Bandanna_aviator";
this addWeapon "hlc_rifle_ak74m_gl";
this addWeapon "CUP_hgun_Phantom";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this setSpeaker "ace_novoice";
