this forceAddUniform "CUP_U_I_GUE_Flecktarn3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addVest "usm_vest_rba";
this addBackpack "CUP_B_RUS_Backpack";
for "_i" from 1 to 7 do {this addItemToBackpack "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_30Rnd_762x39_t_ak";};
this addItemToBackpack "SmokeShell";
this addItemToBackpack "HandGrenade";
this addGoggles "G_Balaclava_oli";
this addWeapon "hlc_rifle_akm";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";