this forceAddUniform "U_B_GEN_Commander_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "hlc_12Rnd_357SIG_B_P226";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 2 do {this addItemToVest "CUP_100Rnd_TE1_Red_Tracer_556x45_BetaCMag";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_100Rnd_TE1_Red_Tracer_556x45_BetaCMag";};
this addHeadgear "CFP_OPS2017_Helmet_Black2";
this addGoggles "SP_Goggles_Black";
this addWeapon "hlc_rifle_M27IAR";
this addPrimaryWeaponItem "CUP_optic_Eotech553_Black";
this addPrimaryWeaponItem "HLC_bipod_UTGShooters";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addWeapon "hlc_pistol_P226R_Stainless";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";