this forceAddUniform "U_B_GEN_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "hlc_12Rnd_357SIG_B_P226";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 4 do {this addItemToVest "CUP_30Rnd_556x45_PMAG_QP_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "CUP_B_USPack_Black";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "CFP_OPS2017_Helmet_Black2";
this addGoggles "CFP_Neck_Wrap2";
this addWeapon "hlc_rifle_416C";
this addPrimaryWeaponItem "ACE_muzzle_mzls_L";
this addPrimaryWeaponItem "CUP_optic_Eotech553_Black";
this addWeapon "hlc_pistol_P226R_Stainless";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";