this forceAddUniform "CUP_O_TKI_Khet_Partug_08";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "10Rnd_9x21_Mag";
this addVest "CUP_V_OI_TKI_Jacket4_02";
for "_i" from 1 to 2 do {this addItemToVest "hlc_75Rnd_762x39_m_rpk";};
this addItemToVest "CUP_HandGrenade_RGD5";
this addBackpack "B_FieldPack_cbr";
for "_i" from 1 to 6 do {this addItemToBackpack "hlc_75Rnd_762x39_m_rpk";};
this addHeadgear "CUP_H_SLA_Helmet";
this addWeapon "hlc_rifle_rpk";
this addWeapon "hgun_Pistol_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
