this forceAddUniform "MNP_CombatUniform_US3Co_A";
this addItemToUniform "CUP_15Rnd_9x19_M9";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "CUP_V_B_RRV_DA1";
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_Carryall_cbr";
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_Watchcap_camo";
this addWeapon "CUP_arifle_M4A3_desert";
this addPrimaryWeaponItem "CUP_optic_CompM2_Desert";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2_Flashlight_Coyote_L";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
