this forceAddUniform "CUP_O_TKI_Khet_Partug_01";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_6Rnd_45ACP_M";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "CUP_V_OI_TKI_Jacket4_05";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
this addItemToVest "CUP_HandGrenade_RGD5";
this addHeadgear "CUP_H_RACS_Beret_Blue";
this addGoggles "G_Aviator";
this addWeapon "hlc_rifle_ak47";
this addWeapon "CUP_hgun_TaurusTracker455_gold";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
