this forceAddUniform "MNP_CombatUniform_US3Co_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_15Rnd_9x19_M9";
this addItemToUniform "Laserbatteries";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addVest "CUP_V_B_RRV_DA1";
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
this addItemToVest "CUP_HandGrenade_M67";
this addBackpack "CUP_B_AssaultPack_Coyote";
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 5 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 5 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "CUP_H_PMC_Cap_PRR_Tan";
this addWeapon "CUP_arifle_M4A1_BUIS_desert_GL";
this addPrimaryWeaponItem "CUP_optic_CompM2_Desert";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2_desert";
this addWeapon "CUP_hgun_M9";
this addWeapon "CUP_SOFLAM";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
