this forceAddUniform "CUP_O_TKI_Khet_Partug_06";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "10Rnd_9x21_Mag";
this addVest "CUP_V_OI_TKI_Jacket4_05";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
this addItemToVest "CUP_HandGrenade_RGD5";
this addBackpack "B_FieldPack_oli";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_30Rnd_762x39_b_ak";};
this addHeadgear "CUP_H_SLA_Helmet";
this addWeapon "hlc_rifle_akm";
this addWeapon "hgun_Pistol_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";