this forceAddUniform "CUP_U_B_CZ_DST_Kneepads_Sleeve";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_CZ_vest16";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "CUP_200Rnd_TE4_Red_Tracer_556x45_M249";
this addBackpack "B_AssaultPack_khk";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_200Rnd_TE4_Red_Tracer_556x45_M249";};
this addHeadgear "CUP_H_CZ_Helmet10";
this addWeapon "CUP_lmg_minimi";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this setFace "WhiteHead_20";
this setSpeaker "ace_novoice";
