
this forceAddUniform "CUP_U_B_CZ_DST_Kneepads_Sleeve";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_30Rnd_556x45_G36";};
this addVest "CUP_V_CZ_vest16";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_30Rnd_556x45_G36";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_30Rnd_TE1_Red_Tracer_556x45_G36";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addHeadgear "CUP_H_CZ_Helmet10";
this addWeapon "CUP_arifle_CZ805_GL";
this addPrimaryWeaponItem "CUP_optic_CompM2_Black";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this setFace "WhiteHead_20";
this setSpeaker "ace_novoice";
