this forceAddUniform "CFP_75th_CRYEG3_V4";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_IR_Strobe_Item";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_FAPC_Operator_Multicam";
for "_i" from 1 to 6 do {this addItemToVest "hlc_30rnd_556x45_M_PMAG";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_t_PMAG";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_15Rnd_9x19_SD_P226";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_M84";};
this addBackpack "CFP_Kitbag_MCam_Grn";
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M";};
this addHeadgear "CFP_OpsC_Covered";
this addGoggles "CFP_Neck_Wrap_Atacs";
this addWeapon "hlc_rifle_416D145_CAG";
this addWeapon "Binocular";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Top_Flashlight_Black_L";
this addPrimaryWeaponItem "CUP_optic_Eotech553_Black";
this addWeapon "hlc_pistol_P226R_Combat";
this addHandgunItem "hlc_muzzle_TiRant9";
this addHandgunItem "CUP_acc_CZ_M3X";
this addHandgunItem "HLC_optic_HP";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "CUP_NVG_GPNVG_black";
