this forceAddUniform "CFP_U_FieldUniform_scorpion_w2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_IR_Strobe_Item";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_FAPC_Operator_OGA";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_M_PMAG";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_15Rnd_9x19_JHP_P226";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_Green";};
this addBackpack "B_AssaultPack_cbr";
this addItemToBackpack "ToolKit";
this addHeadgear "H_CrewHelmetHeli_B";
this addWeapon "hlc_rifle_416C";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Top_Flashlight_Black_L";
this addPrimaryWeaponItem "CUP_optic_Eotech553_Black";
this addWeapon "hlc_pistol_P226R_Combat";
this addHandgunItem "CUP_acc_CZ_M3X";
this addHandgunItem "HLC_optic_HP";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";
