this forceAddUniform "U_O_CombatUniform_ocamo";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_BandollierB_cbr";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 3 do {this addItemToVest "11Rnd_45ACP_Mag";};
this addBackpack "B_Kitbag_cbr";
for "_i" from 1 to 3 do {this addItemToBackpack "150Rnd_93x64_Mag";};
this addHeadgear "H_HelmetO_ocamo";
this addGoggles "G_Balaclava_blk";
this addWeapon "MMG_01_hex_F";
this addPrimaryWeaponItem "bipod_02_F_tan";
this addWeapon "hgun_Pistol_heavy_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
