this forceAddUniform "U_BG_Guerilla1_1";
this addVest "V_TacVest_khk";
for "_i" from 1 to 2 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Yellow";};
this addItemToVest "HandGrenade";
this addItemToVest "SmokeShell";
this addHeadgear "H_ShemagOpen_tan";
this addWeapon "arifle_TRG21_F";
this addPrimaryWeaponItem "optic_ACO_grn";
this addWeapon "rhs_weap_pya";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
