this forceAddUniform "MNP_CombatUniform_RU_Med_DB";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "16Rnd_9x21_Mag";
this addItemToUniform "ACE_Fortify";
this addVest "MNP_Vest_RU_D2";
for "_i" from 1 to 1 do {this addItemToVest "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 10 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_GP25_M";};
this addHeadgear "MNP_Boonie_RU_D";
this addGoggles "G_Bandanna_blk";
this addWeapon "hlc_rifle_ak12GL";
this addWeapon "CUP_hgun_Duty";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
