this forceAddUniform "MNP_CombatUniform_RU_Med_DB";
this addItemToUniform "16Rnd_9x21_Mag";
this addItemToUniform "ACE_Fortify";
this addVest "MNP_Vest_RU_D2";
for "_i" from 1 to 3 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 3 do {this addItemToVest "SmokeShellRed";};
for "_i" from 1 to 10 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addBackpack "MNP_B_RU1_CA";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "MNP_Helmet_RU_LD";
this addGoggles "G_Bandanna_blk";
this addWeapon "hlc_rifle_aku12";
this addWeapon "CUP_hgun_Duty";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
