this forceAddUniform "CUP_U_C_Worker_02";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addVest "V_TacVest_brn";
this addItemToVest "hlc_75Rnd_762x39_AP_rpk";
for "_i" from 1 to 2 do {this addItemToVest "6Rnd_45ACP_Cylinder";};
this addBackpack "CUP_B_HikingPack_Civ";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_75Rnd_762x39_AP_rpk";};
this addHeadgear "CUP_H_C_Beanie_02";
this addWeapon "hlc_rifle_rpk_75rnd";
this addWeapon "hgun_Pistol_heavy_02_F";
this linkItem "ItemCompass";
this linkItem "ItemMap";
this linkItem "ItemWatch";