
this forceAddUniform "CUP_U_O_RUS_EMR_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "CUP_30Rnd_545x39_AK_M";};
this addVest "CUP_V_CZ_vest08";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 1 do {this addItemToVest "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_8Rnd_9x18_Makarov_M";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_545x39_t_ak";};
this addBackpack "CUP_B_RUS_Backpack";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 1 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_GP25_M";};
for "_i" from 1 to 1 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_GP25_M";};
this addHeadgear "CUP_H_RUS_6B27";
this addWeapon "CUP_arifle_AK107_GL";
this addWeapon "CUP_hgun_Makarov";
this addWeapon "Binocular";
this linkItem "ItemGPS";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
