this forceAddUniform "CUP_U_O_RUS_EMR_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addVest "CUP_V_CZ_vest12";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_8Rnd_9x18_Makarov_M";};
this addItemToVest "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M";
this addBackpack "CUP_B_RUS_Backpack";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M";};
this addHeadgear "CUP_H_RUS_6B27";
this addWeapon "CUP_lmg_PKM";
this addWeapon "CUP_hgun_Makarov";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
