removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this addWeapon "hlc_rifle_ACR_Carb_tan";
this addPrimaryWeaponItem "hlc_30rnd_556x45_EPR";
this forceAddUniform "CUP_I_B_PMC_Unit_5";
this addVest "CFP_Smersh_Creme";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 7 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addHeadgear "SP_BeanieHat_Green";
this addGoggles "G_Bandanna_oli";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";