this forceAddUniform "CUP_U_O_Partisan_TTsKO_Mixed";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_O_TK_Vest_1";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_1Rnd_SMOKE_GP25_M";};
this addHeadgear "CUP_H_SLA_BeretRed";
this addWeapon "CUP_arifle_AK74_GL";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
