
this forceAddUniform "usm_bdu_odg";
this addVest "usm_vest_LBE_gr";
for "_i" from 1 to 3 do {this addItemToVest "ACE_fieldDressing";};
this addItemToVest "ACE_morphine";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToVest "CUP_7Rnd_45ACP_1911";};
for "_i" from 1 to 3 do {this addItemToVest "ACE_HandFlare_Green";};
this addItemToVest "ACE_HandFlare_Red";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 7 do {this addItemToVest "RH_20Rnd_556x45";};
for "_i" from 1 to 6 do {this addItemToVest "RH_20Rnd_556x45_Red";};
this addBackpack "CUP_B_AlicePack_Khaki";
for "_i" from 1 to 8 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 12 do {this addItemToBackpack "UGL_FlareRed_F";};
this addItemToBackpack "CUP_HandGrenade_M67";
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_HandFlare_Red";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_HandFlare_Green";};
this addItemToBackpack "SmokeShell";
this addItemToBackpack "ACE_Flashlight_XL50";
this addHeadgear "CUP_H_USArmy_Helmet_M1_Olive";
this addWeapon "RH_M16A1gl";
this addWeapon "CUP_hgun_Colt1911";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";