this forceAddUniform "U_B_CombatUniform_mcam";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "16Rnd_9x21_Mag";};
this addVest "V_PlateCarrier2_rgr";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "150Rnd_556x45_Drum_Mag_F";};
this addBackpack "B_AssaultPack_mcamo";
for "_i" from 1 to 3 do {this addItemToBackpack "150Rnd_556x45_Drum_Mag_Tracer_F";};
this addHeadgear "H_HelmetSpecB_paint1";
this addGoggles "G_Bandanna_oli";
this addWeapon "arifle_SPAR_02_blk_F";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addPrimaryWeaponItem "bipod_01_F_blk";
this addWeapon "hgun_P07_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
