this forceAddUniform "U_O_SpecopsUniform_ocamo";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "10Rnd_9x21_Mag";
this addItemToUniform "ACE_Flashlight_MX991";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_MapTools";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_Chemlight_HiRed";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_HiGreen";};
this addVest "V_HarnessOGL_brn";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 2 do {this addItemToVest "30Rnd_65x39_caseless_green_mag_Tracer";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
this addItemToVest "1Rnd_SmokeRed_Grenade_shell";
this addItemToVest "1Rnd_Smoke_Grenade_shell";
this addItemToVest "SmokeShellGreen";
this addItemToVest "SmokeShellBlue";
this addItemToVest "SmokeShellRed";
for "_i" from 1 to 3 do {this addItemToVest "UGL_FlareRed_F";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_Red";};
this addBackpack "B_AssaultPack_ocamo";
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";
this addItemToBackpack "1Rnd_SmokeBlue_Grenade_shell";
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToBackpack "UGL_FlareRed_F";};
for "_i" from 1 to 4 do {this addItemToBackpack "UGL_FlareYellow_F";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_HandFlare_Red";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_HandFlare_Green";};
for "_i" from 1 to 2 do {this addItemToBackpack "O_IR_Grenade";};
this addHeadgear "H_HelmetLeaderO_ocamo";
this addWeapon "arifle_Katiba_GL_F";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "hgun_Pistol_01_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";
