this forceAddUniform "U_O_CombatUniform_ocamo";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_MX991";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "10Rnd_9x21_Mag";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_Chemlight_HiRed";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_HiGreen";};
this addItemToUniform "ACE_MapTools";
this addItemToUniform "ACE_RangeTable_82mm";
this addVest "V_HarnessO_brn";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 6 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_65x39_caseless_green_mag_Tracer";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_Red";};
this addBackpack "O_Mortar_01_weapon_F";
this addHeadgear "H_HelmetO_ocamo";
this addWeapon "arifle_Katiba_F";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "hgun_Pistol_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";
