this forceAddUniform "CUP_U_B_BAF_DPM_S1_RolledUp";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_CableTie";
this addVest "usm_vest_rba";
for "_i" from 1 to 2 do {this addItemToVest "CUP_17Rnd_9x19_glock17";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_100Rnd_TE4_Red_Tracer_556x45_M249";};
this addItemToBackpack "HandGrenade";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
this addHeadgear "CUP_H_BAF_Officer_Beret";
this addGoggles "CUP_FR_NeckScarf";
this addWeapon "CUP_lmg_L110A1";
this addWeapon "CUP_hgun_Glock17_blk";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";