this forceAddUniform "CUP_U_O_TK_Green";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "10Rnd_9x21_Mag";
this addVest "CUP_V_O_Ins_Carrier_Rig_MG";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
this addItemToVest "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Yellow_M";
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Yellow_M";};
this addHeadgear "H_ShemagOpen_khk";
this addGoggles "G_Bandanna_tan";
this addWeapon "CUP_lmg_PKM";
this addWeapon "hgun_Pistol_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
