this forceAddUniform "CUP_U_I_GUE_Anorak_01";
this addItemToUniform "16Rnd_9x21_Mag";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_RGD5";};
this addVest "V_TacChestrig_grn_F";
for "_i" from 1 to 9 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_VOG25_AK";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_GRD_Red";};
this addGoggles "CUP_RUS_Balaclava_blk";
this addWeapon "hlc_rifle_aks74_GL";
this addWeapon "hgun_Rook40_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
