this forceAddUniform "U_C_HunterBody_grn";
this addItemToUniform "16Rnd_9x21_Mag";
this addVest "V_TacChestrig_oli_F";
for "_i" from 1 to 9 do {this addItemToVest "30Rnd_762x39_Mag_F";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 6 do {this addItemToBackpack "SmokeShell";};
this addHeadgear "H_Bandanna_gry";
this addGoggles "G_Sport_Blackred";
this addWeapon "arifle_AKM_F";
this addWeapon "hgun_Rook40_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
