this call compile preprocessFileLineNumbers "loadouts\blufor\BASE.sqf";
this addBackpack "CUP_B_Kombat_Radio_Olive";
for "_i" from 1 to 4 do {this addItem "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 2 do {this addItem "CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M";};
this addHeadgear "CUP_H_CDF_OfficerCap_FST";
this addWeapon "CUP_arifle_AKS74U";
this addPrimaryWeaponItem "cup_optic_ekp_8_02";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
