this call compile preprocessFileLineNumbers "loadouts\blufor\BASE.sqf";
this addVest "CUP_V_CDF_6B3_4_FST";
this addBackpack "CUP_B_Kombat_Radio_Olive";
for "_i" from 1 to 4 do {this addItem "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 2 do {this addItem "CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M";};
for "_i" from 1 to 2 do {this addItem "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 4 do {this addItem "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 2 do {this addItem "DemoCharge_Remote_Mag";};
this addItem "ACE_DefusalKit";
this addItem "ACE_MapTools";
this addHeadgear "CUP_H_CDF_OfficerCap_FST";
this addWeapon "CUP_arifle_AK74_GL";
this addPrimaryWeaponItem "cup_optic_ekp_8_02";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
