this forceAddUniform "CUP_I_B_PMC_Unit_24";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "hlc_12Rnd_357SIG_B_P226";
this addVest "CUP_V_PMC_CIRAS_Black_Empty";
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Green";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "CUP_B_USPack_Black";
for "_i" from 1 to 6 do {this addItemToBackpack "hlc_50rnd_556x45_EPR";};
this addGoggles "CUP_RUS_Balaclava_blk";
this addWeapon "hlc_rifle_Colt727";
this addWeapon "hlc_pistol_P226R_357Elite";
this addHandgunItem "HLC_optic_Siglite";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";