this forceAddUniform "CUP_U_O_RUS_M88_MSV_rolled_up";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_30Rnd_545x39_AK_M";
this addVest "CUP_V_O_SLA_Flak_Vest03";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_545x39_AK_M";};
this addItemToVest "CUP_HandGrenade_RGO";
this addItemToVest "SmokeShell";
this addBackpack "CUP_B_TK_Medic_Desert";
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "CUP_H_SLA_Helmet_DES";
this addGoggles "CUP_TK_NeckScarf";
this addWeapon "CUP_arifle_AKS74";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";