this forceAddUniform "CUP_U_O_RUS_M88_MSV_rolled_up";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_30Rnd_545x39_AK_M";
this addItemToUniform "CUP_1Rnd_HE_GP25_M";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_1Rnd_SmokeRed_GP25_M";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_1Rnd_SmokeGreen_GP25_M";};
this addVest "CUP_V_O_SLA_Flak_Vest03";
this addItemToVest "CUP_HandGrenade_RGO";
this addItemToVest "SmokeShell";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_1Rnd_SMOKE_GP25_M";};
this addHeadgear "CUP_H_SLA_Helmet_DES";
this addGoggles "CUP_FR_NeckScarf2";
this addWeapon "CUP_arifle_AK74_GL";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";