this forceAddUniform "CUP_U_O_RUS_M88_MSV_rolled_up";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "CUP_V_CDF_CrewBelt";
this addItemToVest "CUP_HandGrenade_RGO";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_30Rnd_545x39_AK_M";};
this addItemToVest "CUP_8Rnd_9x18_Makarov_M";
this addHeadgear "CUP_H_TK_TankerHelmet";
this addWeapon "CUP_arifle_AKS74U";
this addWeapon "CUP_hgun_Makarov";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";