this forceAddUniform "MNP_CombatUniform_Canada_D";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "MNP_VEST_USMC_2";
for "_i" from 1 to 2 do {this addItemToVest "200rndd_556x45_Box_Red_F";};
this addBackpack "B_Kitbag_cbr";
for "_i" from 1 to 2 do {this addItemToBackpack "200rnd_556x45_Box_Red_F";};
this addHeadgear "MNP_Helmet_Canada_D";
this addWeapon "hlc_m249_pip2";
this addPrimaryWeaponItem "optic_aco";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this addGoggles "skn_m04_gas_mask_blk";
