this forceAddUniform "MNP_CombatUniform_Canada_D";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "MNP_VEST_USMC_2";
for "_i" from 1 to 6 do {this addItemToVest "30rnd_556x45_Stanag_green";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_FlareRed_M203";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addHeadgear "MNP_Helmet_Canada_D";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "optic_MRD";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this addGoggles "skn_m04_gas_mask_gre";
