this forceAddUniform "MNP_CombatUniform_Canada_D";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "MNP_VEST_USMC_2";
for "_i" from 1 to 10 do {this addItemToVest "30rnd_556x45_Stanag_green";};
this addBackpack "B_Kitbag_cbr";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "MNP_Helmet_Canada_D";
this addWeapon "hlc_rifle_M4";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this addGoggles "skn_m04_gas_mask_blk";
