this forceAddUniform "MNP_CombatUniform_Ranger_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "MNP_VEST_USMC_2";
for "_i" from 1 to 9 do {this addItemToVest "hlc_30rnd_9x19_B_MP5";};
this addBackpack "B_FieldPack_cbr";
this addItemToBackpack "ToolKit";
this addHeadgear "H_HelmetCrew_B";
this addWeapon "hlc_smg_MP5N";
this addPrimaryWeaponItem "optic_aco";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this addGoggles "skn_m04_gas_mask_blu";
