this forceAddUniform "CUP_U_B_FR_DirAction2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet"; 
this addItemToUniform "ACE_CableTie";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CUP_V_B_Delta_2";
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
this addBackpack "CUP_B_USMC_AssaultPack";
this addItemToBackpack "MRAWS_HEAT55_F";
this addItemToBackpack "MRAWS_HE_F";
this addHeadgear "CUP_H_USArmy_Helmet_ECH1_Green";
this addWeapon "CUP_arifle_Mk16_STD_SFG_black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
