this forceAddUniform "CUP_U_B_FR_SpecOps";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_15Rnd_9x19_M9";
this addVest "CUP_V_B_Eagle_SPC_MG";
this addItemToVest "CUP_15Rnd_9x19_M9";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "SmokeShell";
this addItemToVest "hlc_200rnd_556x45_M_SAW";
this addBackpack "B_Kitbag_cbr";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_200rnd_556x45_M_SAW";};
this addHeadgear "H_HelmetB_light_sand";
this addWeapon "hlc_lmg_mk46";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
