this forceAddUniform "CUP_U_B_FR_SpecOps";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_15Rnd_9x19_M9";
this addVest "CUP_V_B_Eagle_SPC_TL";
for "_i" from 1 to 6 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "SmokeShell";
this addItemToVest "CUP_15Rnd_9x19_M9";
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 5 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "UGL_FlareGreen_F";};
for "_i" from 1 to 2 do {this addItemToBackpack "UGL_FlareRed_F";};
this addHeadgear "H_HelmetB_light_sand";
this addWeapon "CUP_arifle_Mk16_STD_EGLM";
this addPrimaryWeaponItem "CUP_optic_Eotech533";
this addPrimaryWeaponItem "CUP_acc_Flashlight_desert";
this addWeapon "CUP_hgun_M9";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
