removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this addWeapon "hlc_rifle_416D145";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addPrimaryWeaponItem "hlc_30rnd_556x45_EPR";
this forceAddUniform "CFP_U_FieldUniform_marpat_w_light";
this addVest "CUP_V_B_Eagle_SPC_Rifleman";
this addBackpack "CFP_Kitbag_Marpat";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 6 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 3 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 1 do {this addItemToBackpack "ACE_tourniquet";};
this addHeadgear "CFP_PASGTHelmet_Marpat2";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
