removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this addWeapon "hlc_rifle_416D145_gl";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addPrimaryWeaponItem "hlc_30rnd_556x45_EPR";
this addPrimaryWeaponItem "1Rnd_HE_Grenade_shell";
this forceAddUniform "CFP_U_FieldUniform_marpat_w_light";
this addVest "CUP_V_B_Eagle_SPC_Rifleman";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 3 do {this addItemToUniform "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 5 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_HE_M203";};
this addHeadgear "CFP_PASGTHelmet_Marpat2";
this addGoggles "G_Balaclava_combat";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";