this forceAddUniform "MNP_CombatUniform_ISR";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_ISRKahki_2";
for "_i" from 1 to 2 do {this addItemToVest "16Rnd_9x21_Mag";};
this addItemToVest "SmokeShell";
this addItemToVest "SmokeShellGreen";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 4 do {this addItemToVest "ACE_30Rnd_556x45_Stanag_Mk262_mag";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 3 do {this addItemToBackpack "30Rnd_556x45_Stanag_Tracer_Yellow";};
for "_i" from 1 to 2 do {this addItemToBackpack "150Rnd_762x54_Box";};
this addHeadgear "H_HelmetSpecB";
this addGoggles "G_Combat";
this addWeapon "arifle_TRG21_F";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "hgun_P07_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";

