this forceAddUniform "MNP_CombatUniform_ISR";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_ISRKahki_2";
for "_i" from 1 to 2 do {this addItemToVest "16Rnd_9x21_Mag";};
this addItemToVest "SmokeShell";
this addItemToVest "SmokeShellGreen";
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Yellow";};
this addBackpack "B_Kitbag_rgr";
this addHeadgear "CUP_H_USMC_ACVC_WDL";
this addGoggles "G_Combat";
this addWeapon "arifle_TRG21_F";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "hgun_P07_F";
this addWeapon "Binocular";
this linkItem "ItemGPS";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";