this forceAddUniform "CUP_U_O_RUS_Flora_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "MNP_Vest_RU_T2";
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_545x39_t_ak";};
this addBackpack "MNP_B_RU1_FP";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_VOG25_AK";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_GRD_Red";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_GRD_green";};
this addHeadgear "MNP_Helmet_RU_LT";
this addGoggles "G_Bandanna_beast";
this addWeapon "hlc_rifle_ak12GL";
this addWeapon "CUP_hgun_Makarov";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";