this forceAddUniform "U_B_PilotCoveralls";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "CUP_8Rnd_9x18_Makarov_M";};
this addVest "skn_b_nbc_xrt_tac_blk";
for "_i" from 1 to 4 do {this addItemToVest "CUP_64Rnd_9x19_Bizon_M";};
this addItemToVest "SmokeShellOrange";
this addBackpack "ACE_NonSteerableParachute";
this addHeadgear "CUP_H_RUS_ZSH_Shield_Up";
this addGoggles "G_Aviator";
this addWeapon "CUP_smg_bizon";
this addWeapon "CUP_hgun_Makarov";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";