this forceAddUniform "CUP_U_O_RUS_Flora_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addVest "MNP_Vest_RU_T2";
for "_i" from 1 to 7 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_545x39_t_ak";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_8Rnd_9x18_Makarov_M";};
this addBackpack "MNP_B_RU1_FP";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_VOG25_AK";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_GRD_Red";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_GRD_green";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_GRD_orange";};
for "_i" from 1 to 3 do {this addItemToBackpack "SmokeShellOrange";};
for "_i" from 1 to 3 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 3 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
this addItemToBackpack "HandGrenade";
this addHeadgear "MNP_Helmet_RU_LT";
this addGoggles "G_Bandanna_khk";
this addWeapon "hlc_rifle_ak12GL";
this addWeapon "CUP_hgun_Makarov";
this addWeapon "Laserdesignator";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";