this forceAddUniform "CUP_U_B_FR_Scout3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Clacker";
for "_i" from 1 to 3 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr";
for "_i" from 1 to 8 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 8 do {this addItemToVest "CUP_FlareRed_M203";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addBackpack "CUP_B_USMC_AssaultPack";
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addHeadgear "CUP_H_USArmy_Helmet_ECH1_Green";
this addWeapon "CUP_arifle_Mk16_STD_EGLM_black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "cup_optic_mrad";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this addItemToBackpack "DemoCharge_Remote_Mag";
this addItemToBackpack "DemoCharge_Remote_Mag";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ACE_Altimeter";
this linkItem "ItemGPS";