this forceAddUniform "CUP_U_B_USArmy_UBACS";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACRE_PRC343";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CUP_V_B_IOTV_Rifleman";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "CUP_30Rnd_556x45_Stanag";
this addBackpack "CUP_B_AssaultPack_ACU";
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_Smoke_M203";};
this addHeadgear "CUP_H_USArmy_HelmetMICH_headset_ess";
this addWeapon "CUP_arifle_M4A1_BUIS_GL";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";
this linkItem "ItemGPS";