this forceAddUniform "CUP_O_TKI_Khet_Partug_07";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "hlc_30Rnd_762x39_b_ak";
this addItemToUniform "ACE_Fortify";
this addVest "CUP_V_RUS_Smersh_1";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
this addBackpack "CUP_B_AlicePack_Khaki";
for "_i" from 1 to 10 do {this addItemToBackpack "hlc_45Rnd_762x39_m_rpk";};
this addHeadgear "CUP_H_TKI_SkullCap_05";
this addWeapon "hlc_rifle_akm";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";