this forceAddUniform "CUP_O_TKI_Khet_Partug_03";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addVest "CUP_V_O_Ins_Carrier_Rig_MG";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 5 do {this addItemToVest "hlc_45Rnd_762x39_m_rpk";};
this addBackpack "CUP_B_AlicePack_Khaki";
for "_i" from 1 to 12 do {this addItemToBackpack "hlc_45Rnd_762x39_m_rpk";};
this addHeadgear "H_ShemagOpen_khk";
this addWeapon "hlc_rifle_rpk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";