this forceAddUniform "CUP_O_TKI_Khet_Jeans_02";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addItemToUniform "hlc_30Rnd_762x39_b_ak";
this addVest "CUP_V_RUS_Smersh_1";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_VOG25_AK";};
this addBackpack "usm_pack_st138_prc77";
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_VOG25_AK";};
this addItemToBackpack "CUP_1Rnd_SmokeRed_GP25_M";
this addItemToBackpack "CUP_1Rnd_SmokeGreen_GP25_M";
this addHeadgear "CUP_H_TKI_Lungee_Open_05";
this addWeapon "hlc_rifle_akmgl";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";