this forceAddUniform "CUP_O_TKI_Khet_Partug_02";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addItemToUniform "hlc_30Rnd_762x39_b_ak";
this addVest "CUP_V_O_Ins_Carrier_Rig_Light";
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
this addBackpack "usm_pack_alice_prc77";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 6 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "CUP_H_TKI_Pakol_2_04";
this addGoggles "G_Squares";
this addWeapon "hlc_rifle_akm";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";