this forceAddUniform "usm_bdu_odg";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addVest "usm_vest_lbv_rmp_m";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 8 do {this addItemToVest "hlc_20Rnd_762x51_B_M14";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_7Rnd_45ACP_1911";};
this addBackpack "usm_pack_762x51_bandoliers";
for "_i" from 1 to 8 do {this addItemToBackpack "hlc_100Rnd_762x51_M_M60E4";};
this addHeadgear "CUP_H_USArmy_Helmet_M1_Olive";
this addWeapon "hlc_rifle_M14_Bipod";
this addWeapon "CUP_hgun_Colt1911";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";