this forceAddUniform "CUP_O_TKI_Khet_Partug_06";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
this addItemToUniform "hlc_30Rnd_762x39_b_ak";
this addVest "CUP_V_O_Ins_Carrier_Rig_Light";
this addItemToVest "CUP_HandGrenade_M67";
this addItemToVest "SmokeShell";
for "_i" from 1 to 7 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
this addBackpack "CUP_B_RPGPack_Khaki";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_PG7V_M";};
this addItemToBackpack "CUP_OG7_M";
this addHeadgear "CUP_H_TKI_Lungee_01";
this addWeapon "hlc_rifle_akm";
this addWeapon "CUP_launch_RPG7V";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";