this forceAddUniform "U_TIOW_Fire_Warrior";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addVest "TIOW_Tau_Belt_Shasui";
for "_i" from 1 to 14 do {this addItemToVest "TIOW_pulse_mag";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addBackpack "TIOW_Tau_Bck_Strike_Shasui";
this addHeadgear "TIOW_Tau_Hset3";
this addWeapon "TIOW_pulse_carbine_ML";
this addPrimaryWeaponItem "TIOW_Tau_optics_ColiB";
this addWeapon "Rangefinder";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
[this,"tau_male_5","ace_novoice"] call BIS_fnc_setIdentity;