this forceAddUniform "U_TIOW_Pathfinder";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "Laserbatteries";};
this addVest "TIOW_Tau_BeltP_Shasui";
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 13 do {this addItemToVest "TIOW_pulse_mag";};
this addBackpack "TIOW_Tau_Bck_Phndr_Shasui";
for "_i" from 1 to 8 do {this addItemToBackpack "TIOW_ionrifle_overcharge_mag";};
this addHeadgear "TIOW_Tau_HelmetP_sui";
this addWeapon "TIOW_pulse_carbine_ML";
this addPrimaryWeaponItem "TIOW_Tau_optics_ColiS";
this addWeapon "Laserdesignator";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
[this,"tau_male_4","ace_novoice"] call BIS_fnc_setIdentity;