this forceAddUniform "CUP_I_B_PMC_Unit_28";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_BAF_MTP_Osprey_Mk4_AutomaticRifleman";
this addItemToVest "CUP_200Rnd_TE4_Red_Tracer_556x45_M249";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A2_HE";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addBackpack "CUP_B_Bergen_BAF";
for "_i" from 1 to 1 do {this addItemToBackpack "CUP_200Rnd_TE4_Red_Tracer_556x45_L110A1";};
this addHeadgear "CUP_H_BAF_MTP_Mk6_GOGGLES_PRR";
this addWeapon "CUP_lmg_L110A1";
this addPrimaryWeaponItem "CUP_optic_Eotech553_Black";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
