this forceAddUniform "CUP_I_B_PMC_Unit_28";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_BAF_Osprey_Mk2_DPM_Pilot";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addBackpack "CUP_B_Bergen_BAF";
this addItemToBackpack "ToolKit";
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addHeadgear "H_PilotHelmetHeli_B";
this addWeapon "CUP_arifle_L85A2_NG";
this addPrimaryWeaponItem "CUP_optic_Eotech553_Black";
this addWeapon "CUP_hgun_Glock17_blk";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
