this forceAddUniform "rhs_uniform_cu_ucp_10th";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_IR";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "rhsusf_mag_17Rnd_9x19_FMJ";};
this addVest "rhsusf_iotv_ucp_SAW";
this addItemToVest "rhs_200rnd_556x45_B_SAW";
this addWeapon "rhs_weap_m249_pip";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_200rnd_556x45_B_SAW";};
this addHeadgear "rhsusf_ach_helmet_headset_ess_ucp";
this addPrimaryWeaponItem "rhsusf_acc_SFMB556";
this addPrimaryWeaponItem "rhsusf_acc_eotech_552";
this addWeapon "rhsusf_weap_glock17g4";
this addHandgunItem "acc_flashlight_pistol";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "rhsusf_ANPVS_15";
