this forceAddUniform "rhs_uniform_cu_ucp";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_IR";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "rhsusf_mag_17Rnd_9x19_FMJ";};
this addVest "rhsusf_iotv_ucp_Repair";
for "_i" from 1 to 7 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m18_purple";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
this addBackpack "B_AssaultPack_blk";
this addItemToBackpack "ToolKit";
this addHeadgear "rhsusf_hgu56p";
this addWeapon "rhs_weap_m4_carryhandle_mstock";
this addWeapon "rhsusf_weap_glock17g4";
this addHandgunItem "acc_flashlight_pistol";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "rhsusf_ANPVS_15";
