this forceAddUniform "CUP_U_B_BAF_DDPM_UBACSTSHIRTKNEE";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_Chemlight_HiRed";};
this addVest "CUP_V_B_BAF_DDPM_Osprey_Mk3_Rifleman";
this addItemToVest "ACE_EntrenchingTool";
this addBackpack "CUP_B_Kombat_Olive";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_200Rnd_TE1_Red_Tracer_556x45_M249";};
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_556x45_Stanag_L85_Tracer_Red";};
this addHeadgear "CUP_H_BAF_DDPM_Mk6_EMPTY";
this addWeapon "CUP_arifle_L85A2_G";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Flashlight_Black_L";
this addPrimaryWeaponItem "optic_Holosight_smg_blk_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";