this forceAddUniform "CUP_U_O_RUS_EMR_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";

this addVest "CUP_V_CZ_vest04";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_RGD5";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_8Rnd_9x18_Makarov_M";};
this addBackpack "CUP_B_RPGPack_Khaki";
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_PG7V_M";};
this addHeadgear "CUP_H_RUS_6B27";
this addWeapon "CUP_arifle_AK107";
this addWeapon "CUP_launch_RPG7V";
this addWeapon "CUP_hgun_Makarov";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";