this forceAddUniform "rhs_uniform_msv_emr";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_CableTie";
this addVest "rhs_6b23_6sh116_od";
this addItemToVest "rhs_100Rnd_762x54mmR_green";
this addWeapon "rhs_weap_pkp";
this addItemToVest "rhs_100Rnd_762x54mmR_green";
for "_i" from 1 to 2 do {this addItemToVest "rhsusf_mag_17Rnd_9x19_JHP";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_black";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rgd5";};
this addBackpack "rhs_assault_umbts";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_100Rnd_762x54mmR_green";};
this addHeadgear "rhs_6b7_1m_emr_ess_bala";
this addWeapon "rhsusf_weap_glock17g4";
this addHandgunItem "acc_flashlight_pistol";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
