this forceAddUniform "rhs_uniform_msv_emr";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_CableTie";
for "_i" from 1 to 2 do {this addItemToUniform "9Rnd_45ACP_Mag";};
for "_i" from 1 to 2 do {this addItemToUniform "rhs_mag_rdg2_black";};
this addVest "rhs_6b23_6sh116_od";
for "_i" from 1 to 9 do {this addItemToVest "rhs_30Rnd_762x39mm_tracer";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rgd5";};
this addBackpack "rhs_assault_umbts";
for "_i" from 1 to 5 do {this addItemToBackpack "rhs_VOG25";};
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_GRD40_White";};
this addHeadgear "rhs_6b7_1m_emr_ess_bala";
this addWeapon "rhs_weap_ak103_gp25";
this addPrimaryWeaponItem "rhs_acc_dtk3";
this addPrimaryWeaponItem "rhs_acc_2dpZenit";
this addWeapon "hgun_ACPC2_F";
this addHandgunItem "acc_flashlight_pistol";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
