this forceAddUniform "MNP_CombatUniform_Militia_DA";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACRE_PRC343";
this addVest "MNP_Vest_Olive_1";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M";};
this addItemToVest "CUP_HandGrenade_M67";
this addBackpack "B_Kitbag_cbr";
for "_i" from 1 to 40 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 25 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 25 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 9 do {this addItemToBackpack "SmokeShellBlue";};
this addHeadgear "CUP_H_TK_Helmet";
this addWeapon "CUP_arifle_AK74";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
[this,"MedB"] call bis_fnc_setUnitInsignia;
