this forceAddUniform "MNP_CombatUniform_DS_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_IR_Strobe_Item";
this addVest "CUP_V_B_RRV_DA1";
for "_i" from 1 to 2 do {this addItemToVest "CUP_17Rnd_9x19_glock17";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "ACE_M84";};
this addItemToVest "CUP_100Rnd_556x45_BetaCMag_ar15";
this addBackpack "B_AssaultPack_cbr";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_100Rnd_556x45_BetaCMag_ar15";};
this addHeadgear "CUP_H_USArmy_Helmet_ECH1_Sand";
this addWeapon "CUP_arifle_HK_M27";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_Glock17_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
