this forceAddUniform "CUP_U_I_RACS_PilotOverall";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_epinephrine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_MTV";
for "_i" from 1 to 3 do {this addItemToVest "11Rnd_45ACP_Mag";};
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_9x19_SD_MP5";};
this addBackpack "B_Parachute";
this addHeadgear "H_PilotHelmetHeli_B";
this addWeapon "CUP_smg_MP5SD6";
this addWeapon "hgun_Pistol_heavy_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";