this forceAddUniform "MNP_CombatUniform_NOR_B";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
 for "_i" from 1 to 3 do {this addItemToVest "CUP_18Rnd_9x19_Phantom";};
this addVest "MNP_Vest_NOR_2";
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 7 do {this addItemToVest "ACE_30Rnd_556x45_Stanag_Mk318_mag";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 7 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 4 do {this addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
this addHeadgear "MNP_Helmet_DS";
this addGoggles "G_Bandanna_oli";
this addWeapon "arifle_SPAR_01_GL_blk_F";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "CUP_hgun_Phantom";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";