this forceAddUniform "U_BG_leader";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addVest "V_TacVest_camo";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_545x39_t_ak";};
this addWeapon "hlc_rifle_ak74_dirty2";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";