this forceAddUniform "U_BG_leader";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 2 do {this addItemToUniform "hlc_30Rnd_545x39_B_AK";};
this addVest "V_TacVest_camo";
this addBackpack "CUP_B_CivPack_WDL";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 5 do {this addItemToBackpack "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_30Rnd_545x39_t_ak";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_VOG25_AK";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_GRD_White";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_GRD_Red";};
this addGoggles "G_Bandanna_oli";
this addWeapon "hlc_rifle_ak74m_gl";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";