this forceAddUniform "CUP_U_C_Rocker_01";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addBackpack "usm_pack_abag_m60";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_10Rnd_9x19_B_P239";};
this addWeapon "hlc_pistol_P239";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";