this forceAddUniform "CUP_U_C_Suit_01";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "hlc_30Rnd_762x39_b_ak";
this addBackpack "usm_pack_abag_m60";
this addItemToBackpack "hlc_rifle_slr107u";
this addItemToBackpack "hlc_30Rnd_762x39_b_ak";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";