this forceAddUniform "U_BG_leader";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addVest "V_TacVest_camo";
this addBackpack "CUP_B_CivPack_WDL";
for "_i" from 1 to 5 do {this addItemToBackpack "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_30Rnd_545x39_t_ak";};
this addItemToBackpack "ACE_PreloadedMissileDummy_M72A6_CUP";
this addWeapon "hlc_rifle_ak74_dirty";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";