this forceAddUniform "CUP_U_B_USMC_MARPAT_WDL_Sleeves";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
this addVest "V_PlateCarrier1_rgr";
this addItemToVest "CUP_200Rnd_TE1_Red_Tracer_556x45_M249";
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_Red";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_200Rnd_TE1_Red_Tracer_556x45_M249";};
this addHeadgear "CUP_H_USMC_LWH_NVGMOUNT_WDL";
this addGoggles "G_Combat";
this addWeapon "hlc_m249_pip4";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addItemToVest "CUP_200Rnd_TE1_Red_Tracer_556x45_M249";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
