this forceAddUniform "CUP_U_B_USMC_MARPAT_WDL_Sleeves";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
this addVest "V_PlateCarrier1_rgr";
for "_i" from 1 to 10 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_Red";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_Kitbag_cbr";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "CUP_H_USMC_LWH_NVGMOUNT_WDL";
this addGoggles "G_Combat";
this addWeapon "hlc_rifle_M4";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
