this forceAddUniform "CFP_U_WorkUniform_Flecktarn";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addVest "CFP_Modular1_Flecktarn";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30rnd_556x45_EPR_G36";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_30rnd_556x45_Tracers_G36";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "hlc_12Rnd_357SIG_B_P226";
this addBackpack "CFP_Kitbag_Flecktarn";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200rnd_556x45_T_SAW";};
this addHeadgear "CFP_PASGTHelmet_Flecktarn2";
this addWeapon "hlc_rifle_G36V";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P226R_Stainless";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";