this forceAddUniform "CFP_U_WorkUniform_Flecktarn";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addVest "CFP_Modular1_Flecktarn";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addItemToVest "hlc_12Rnd_357SIG_B_P226";
for "_i" from 1 to 5 do {this addItemToVest "hlc_30rnd_556x45_EPR_G36";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_30rnd_556x45_Tracers_G36";};
this addBackpack "CFP_AssaultPack_Flecktarn";
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "CFP_PASGTHelmet_Flecktarn2";
this addGoggles "G_Bandanna_beast";
this addWeapon "hlc_rifle_G36VAG36";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P226R_Stainless";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";