this forceAddUniform "CUP_U_B_FR_DirAction2";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet"; 
this addItemToUniform "ACE_CableTie";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr";
for "_i" from 1 to 3 do {this addItemToVest "CUP_100Rnd_TE4_Red_Tracer_556x45_M249";};
this addBackpack "CUP_B_USMC_AssaultPack";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_100Rnd_TE4_Red_Tracer_556x45_M249";};
this addHeadgear "CUP_H_USMC_Headset_HelmetWDL";
this addWeapon "CUP_lmg_m249_pip1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";