this forceAddUniform "CUP_U_B_FR_Scout3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet"; 
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_MapTools";
this addItemToUniform "ACE_RangeTable_82mm";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr";
for "_i" from 1 to 7 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 10 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addItemToVest "CUP_17Rnd_9x19_glock17";
this addBackpack "CUP_B_M252_Bipod_Bag";
this addHeadgear "CUP_H_USMC_Headset_HelmetWDL";
this addWeapon "CUP_arifle_Mk16_STD_EGLM_black";
this addPrimaryWeaponItem "cup_optic_mrad";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this addHandgunItem "optic_MRD";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";