this forceAddUniform "U_B_CTRG_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_PlateCarrierL_CTRG";
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_10Rnd_40sw_JHP_P229";};
for "_i" from 1 to 6 do {this addItemToVest "ACE_30Rnd_556x45_Stanag_Mk318_mag";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 3 do {this addItemToVest "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 3 do {this addItemToVest "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 3 do {this addItemToVest "1Rnd_SmokeGreen_Grenade_shell";};
this addHeadgear "H_HelmetSpecB_paint1";
this addGoggles "G_Bandanna_beast";
this addWeapon "CUP_arifle_L85A2_GL";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "hlc_pistol_P229R_40Elite";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";