this forceAddUniform "U_B_CTRG_1";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_PlateCarrierL_CTRG";
for "_i" from 1 to 7 do {this addItemToVest "ACE_30Rnd_556x45_Stanag_Mk318_mag";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_10Rnd_40sw_JHP_P229";};
this addHeadgear "H_HelmetSpecB_paint1";
this addWeapon "CUP_arifle_L85A2_G";
this addPrimaryWeaponItem "CUP_optic_CompM4";
this addWeapon "CUP_launch_M136";
this addWeapon "hlc_pistol_P229R_40Elite";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";