this forceAddUniform "MNP_CombatUniform_OD_Sh";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_6Rnd_45ACP_M";
this addVest "V_TacVest_khk";
for "_i" from 1 to 10 do {this addItemToVest "CUP_5x_22_LR_17_HMR_M";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellRed";};
this addHeadgear "CUP_H_PMC_Cap_EP_Tan";
this addWeapon "CUP_srifle_CZ550_rail";
this addPrimaryWeaponItem "CUP_optic_MRad";
this addWeapon "CUP_hgun_TaurusTracker455";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
