this forceAddUniform "rhs_uniform_gorka_r_g";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhs_6b23_6sh116_od";
for "_i" from 1 to 7 do {this addItemToVest "rhs_20rnd_9x39mm_SP5";};
this addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_white";};
this addBackpack "rhs_assault_umbts";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_100Rnd_762x54mmR";};
this addHeadgear "rhs_6b27m_digi_bala";
this addWeapon "rhs_weap_asval_grip";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
