this forceAddUniform "rhs_uniform_gorka_r_g";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhs_6b23_6sh116_od";
for "_i" from 1 to 6 do {this addItemToVest "rhs_30Rnd_545x39_AK";};
this addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 3 do {this addItemToVest "rhs_mag_rdg2_white";};
this addHeadgear "rhs_6b27m_digi_bala";
this addWeapon "rhs_weap_ak74m_2mag_camo";
this addPrimaryWeaponItem "rhs_acc_dtk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
