this forceAddUniform "CUP_U_O_RUS_VSR98_worn_gloves_VDV";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_FAPC_MG_OGA_OD";
this addItemToVest "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_green";};
this addItemToVest "HandGrenade";
this addBackpack "MNP_B_RU2_CA";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M";};
this addHeadgear "CUP_H_RUS_6B47";
this addWeapon "CUP_lmg_Pecheneg";
this addWeapon "hgun_Rook40_F";
this addHandgunItem "16Rnd_9x21_Mag";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
