this forceAddUniform "CUP_U_O_RUS_VSR98_worn_gloves_VDV";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_FAPC_Operator_OGA_OD";
for "_i" from 1 to 6 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30Rnd_545x39_t_ak";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_green";};
this addItemToVest "HandGrenade";
this addHeadgear "CUP_H_RUS_6B47";
this addWeapon "hlc_rifle_aku12";
this addPrimaryWeaponItem "CUP_optic_Eotech553_Black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addWeapon "hgun_Rook40_F";
this addHandgunItem "16Rnd_9x21_Mag";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
