this forceAddUniform "CUP_U_I_GUE_Flecktarn3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_Fortify";
this addVest "usm_vest_rba";
for "_i" from 1 to 2 do {this addItemToVest "CUP_18Rnd_9x19_Phantom";};
this addBackpack "CUP_B_RUS_Backpack";
this addItemToBackpack "SmokeShell";
this addItemToBackpack "HandGrenade";
for "_i" from 1 to 7 do {this addItemToBackpack "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M";};
for "_i" from 1 to 5 do {this addItemToBackpack "hlc_45Rnd_762x39_m_rpk";};
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_45Rnd_762x39_t_rpk";};
this addGoggles "G_Balaclava_oli";
this addWeapon "CUP_arifle_AK74";
this addWeapon "CUP_hgun_Phantom";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";