this forceAddUniform "CUP_U_I_GUE_Flecktarn3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_Fortify";
this addVest "usm_vest_rba";
for "_i" from 1 to 2 do {this addItemToVest "CUP_18Rnd_9x19_Phantom";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 7 do {this addItemToBackpack "ACE_personalAidKit";};
for "_i" from 1 to 5 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_30Rnd_545x39_AK_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M";};
this addGoggles "G_Balaclava_oli";
this addWeapon "CUP_arifle_AK74";
this addWeapon "CUP_hgun_Phantom";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";