this forceAddUniform "CUP_U_I_GUE_Flecktarn3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_Fortify";
this addVest "usm_vest_rba";
for "_i" from 1 to 2 do {this addItemToVest "CUP_18Rnd_9x19_Phantom";};
this addBackpack "CUP_B_RUS_Backpack";
this addItemToBackpack "SmokeShell";
this addItemToBackpack "HandGrenade";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M";};
this addGoggles "G_Balaclava_oli";
this addWeapon "CUP_lmg_Pecheneg";
this addWeapon "CUP_hgun_Phantom";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";