this forceAddUniform "MNP_CombatUniform_USMC_arctic";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Fortify";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CUP_V_PMC_CIRAS_Winter_Patrol";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30rnd_556x45_Tracers_G36";};
this addBackpack "MNP_B_WB_KB";
for "_i" from 1 to 3 do {this addItemToBackpack "Titan_AT";};
this addHeadgear "MNP_Helmet_USMC_arctic";
this addWeapon "hlc_rifle_G36C";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addPrimaryWeaponItem "acc_flashlight";
this addWeapon "launch_B_Titan_short_tna_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this addGoggles "G_Balaclava_blk";
