this forceAddUniform "U_B_CTRG_Soldier_F";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr_noflag_F";
for "_i" from 1 to 6 do {this addItemToVest "hlc_30rnd_556x45_Tracers_G36";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_FlareRed_M203";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addItemToVest "30rnd_9x21_Yellow_Mag";
this addItemToVest "ACE_IR_Strobe_Item";
this addBackpack "B_ViperHarness_oli_F";
for "_i" from 1 to 5 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 5 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
for "_i" from 1 to 10 do {this addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
for "_i" from 1 to 5 do {this addItemToBackpack "UGL_FlareGreen_F";};
for "_i" from 1 to 5 do {this addItemToBackpack "UGL_FlareRed_F";};
this addHeadgear "H_HelmetB_TI_tna_F";
this addWeapon "HLC_Rifle_G36KSKAG36";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this addWeapon "hgun_P07_khk_F";
this addWeapon "Laserdesignator_01_khk_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkitem "arcore_nightvision_Gen8";
this addGoggles "G_Balaclava_TI_G_tna_F";
