this forceAddUniform "U_B_HeliPilotCoverAlls";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_TacVest_blk";
for "_i" from 1 to 5 do {this addItemToVest "30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_Chemlight_HiRed";};
this addItemToVest "ACE_HandFlare_Red";
this addItemToVest "ACE_HandFlare_Green";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellPurple";};
this addHeadgear "H_PilotHelmetHeli_B";
this addWeapon "SMG_01_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen8";
