removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this forceAddUniform "U_B_T_Soldier_SL_F";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACRE_PRC148_ID_2";
this addItemToUniform "ACRE_PRC343_ID_2";
this addItemToUniform "ACE_Fortify";
for "_i" from 1 to 3 do {this addItemToUniform "30Rnd_556x45_Stanag_Tracer_Red";};
this addVest "V_PlateCarrier1_tna_F";
this addItemToVest "ACE_CableTie";
this addItemToVest "ACE_EarPlugs";
this addItemToVest "ACE_EntrenchingTool";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 4 do {this addItemToVest "ACE_salineIV_500";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_salineIV_250";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_AssaultPack_dgtl";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_HelmetB_tna_F";
this addWeapon "arifle_Mk20_F";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "hgun_Rook40_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";
this linkItem "ItemGPS";
