removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this forceAddUniform "U_B_T_Soldier_SL_F";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
for "_i" from 1 to 3 do {this addItemToUniform "30Rnd_556x45_Stanag_Tracer_Red";};
this addItemToUniform "16Rnd_9x21_Mag";
this addVest "V_PlateCarrier1_tna_F";
this addItemToVest "ACE_CableTie";
this addItemToVest "ACE_EarPlugs";
this addItemToVest "ACE_EntrenchingTool";
this addItemToVest "ACE_tourniquet";
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 2 do {this addItemToVest "1Rnd_HE_Grenade_shell";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "B_AssaultPack_dgtl";
this addItemToBackpack "RPG7_F";
this addHeadgear "H_HelmetB_tna_F";
this addWeapon "arifle_Mk20_F";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "launch_RPG7_F";
this addWeapon "hgun_Rook40_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";
this linkItem "ItemGPS";
