this forceAddUniform "U_BG_Guerrilla_6_1";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "16Rnd_9x21_Mag";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
this addVest "CUP_V_PMC_CIRAS_Black_Patrol";
for "_i" from 1 to 3 do {this addItemToVest "hlc_60Rnd_545x39_t_rpk";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_M84";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_Watchcap_camo";
this addGoggles "CUP_FR_NeckScarf";
this addWeapon "hlc_rifle_ak12";
this addPrimaryWeaponItem "hlc_muzzle_545SUP_AK";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addItemToVest "hlc_60Rnd_545x39_t_rpk";
this addWeapon "hgun_Rook40_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "arcore_nightvision_Gen5";
