this forceAddUniform "CUP_I_B_PMC_Unit_19";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_HandGrenade_M67";
this addItemToUniform "SmokeShell";
this addVest "V_I_G_resistanceLeader_F";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_75Rnd_762x39_m_rpk";};
this addHeadgear "H_Bandanna_blu";
this addGoggles "G_Sport_Red";
this addWeapon "hlc_rifle_aks74";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";