this forceAddUniform "CUP_I_B_PMC_Unit_3";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_HandGrenade_M67";
this addItemToUniform "SmokeShell";
this addVest "V_TacVest_oli";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addBackpack "B_AssaultPack_rgr";
for "_i" from 1 to 5 do {this addItemToBackpack "CUP_1Rnd_HE_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SMOKE_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_GP25_M";};
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_GP25_M";};
this addHeadgear "usm_bdu_cap_tgrstp";
this addGoggles "CUP_FR_NeckScarf";
this addWeapon "hlc_rifle_ak74m_gl";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";