this forceAddUniform "CUP_I_B_PMC_Unit_22";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "CUP_HandGrenade_M67";
this addItemToUniform "SmokeShell";
this addVest "V_I_G_resistanceLeader_F";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addHeadgear "usm_bdu_boonie_portliz";
this addWeapon "hlc_rifle_ak74";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";