this forceAddUniform "usm_bdu_dcu_m";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_PlateCarrier1_rgr";
this addItemToVest "CUP_17Rnd_9x19_glock17";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
this addItemToVest "hlc_200rnd_556x45_M_SAW";
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 3 do {this addItemToBackpack "hlc_200rnd_556x45_M_SAW";};
this addHeadgear "CUP_H_PMC_Cap_Back_EP_Tan";
this addGoggles "G_Bandanna_tan";
this addWeapon "hlc_m249_pip2";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "CUP_hgun_Glock17_tan";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
