this forceAddUniform "usm_bdu_dcu_m";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "MNP_Vest_USMC_2";
this addItemToVest "CUP_17Rnd_9x19_glock17";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
for "_i" from 1 to 10 do {this addItemToVest "30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 4 do {this addItemToVest "CUP_1Rnd_SmokeRed_M203";};
this addHeadgear "usm_bdu_boonie_dcu";
this addGoggles "G_Bandanna_tan";
this addWeapon "arifle_SPAR_01_GL_snd_F";
this addPrimaryWeaponItem "muzzle_snds_m_snd_F";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "CUP_hgun_Glock17_tan";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
