this forceAddUniform "usm_bdu_dcu_m";
this addVest "V_PlateCarrier2_rgr";
this addItemToVest "CUP_17Rnd_9x19_glock17";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 10 do {this addItemToVest "30Rnd_556x45_Stanag";};
this addBackpack "CUP_B_USMC_AssaultPack";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "usm_bdu_8point_dcu_m";
this addGoggles "G_Bandanna_tan";
this addWeapon "arifle_SPAR_01_snd_F";
this addPrimaryWeaponItem "muzzle_snds_m_snd_F";
this addPrimaryWeaponItem "optic_Holosight";
this addWeapon "CUP_hgun_Glock17_tan";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
