this forceAddUniform "U_I_C_Soldier_Para_3_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_BandollierB_khk";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30Rnd_545x39_B_AK";};
this addItemToVest "CUP_HandGrenade_RGD5";
this addBackpack "CUP_B_RPGPack_Khaki";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_OG7_M";};
this addHeadgear "CUP_H_RUS_6B27_olive";
this addGoggles "CUP_FR_NeckScarf2";
this addWeapon "hlc_rifle_aks74u";
this addWeapon "CUP_launch_RPG7V";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
