this forceAddUniform "SP_0000_Standard_BattleDressUniform_NodUrban";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "SP_Modular1_White";
for "_i" from 1 to 2 do {this addItemToVest "130Rnd_338_Mag";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "CFP_AssaultPack_White";
for "_i" from 1 to 2 do {this addItemToBackpack "130Rnd_338_Mag";};
this addHeadgear "SP_M1Helmet_UN";
this addWeapon "MMG_02_camo_F";
this addPrimaryWeaponItem "ACE_muzzle_mzls_338";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_15_Flashlight_Tan_L";
this addPrimaryWeaponItem "optic_Holosight";
this addPrimaryWeaponItem "bipod_01_F_blk";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "SP_MouthScarf_White";