this forceAddUniform "SP_0000_Standard_BattleDressUniform_NodUrban";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "SP_Modular1_White";
for "_i" from 1 to 4 do {this addItemToVest "hlc_30Rnd_556x45_EPR_sg550";};
this addItemToVest "CUP_HandGrenade_M67";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
this addBackpack "CFP_AssaultPack_White";
this addHeadgear "SP_CVCHelmet_UN";
this addWeapon "hlc_rifle_SG553SB";
this addPrimaryWeaponItem "CUP_muzzle_mfsup_SCAR_L";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "SP_MouthScarf_White";