this forceAddUniform "U_B_CTRG_Soldier_F";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr_noflag_F";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30rnd_556x45_Tracers_G36";};
this addBackpack "B_ViperHarness_oli_F";
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_HelmetB_TI_tna_F";
this addWeapon "hlc_rifle_G36C";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
