this forceAddUniform "U_B_CTRG_Soldier_F";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr_noflag_F";
for "_i" from 1 to 2 do {this addItemToVest "130rnd_338_Mag";};
this addBackpack "B_ViperHarness_oli_F";
for "_i" from 1 to 3 do {this addItemToBackpack "130rnd_338_Mag";};
this addHeadgear "H_HelmetB_TI_tna_F";
this addWeapon "MMG_02_black_F";
this addPrimaryWeaponItem "optic_holosight_blk_f";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
