this forceAddUniform "MNP_CombatUniform_Canada";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
this addItemToUniform "ACE_CableTie";
this addVest "MNP_Vest_Canada_T";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30rnd_556x45_TDim";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_M84";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "B_IR_Grenade";};
this addBackpack "B_AssaultPack_blk";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200rnd_556x45_Mdim_SAW";};
this addHeadgear "H_HelmetB_Light_tna_F";
this addGoggles "G_Bandanna_blk";
this addWeapon "hlc_rifle_CQBR";
this addPrimaryWeaponItem "hlc_muzzle_snds_AUG";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this linkItem "ItemMap";
this linkItem "ItemGPS";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";
