this forceAddUniform "MNP_CombatUniform_Canada";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "CUP_17Rnd_9x19_glock17";
this addItemToUniform "ACE_CableTie";
this addVest "MNP_Vest_Canada_T";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30rnd_556x45_TDim";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_M84";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "B_IR_Grenade";};
this addBackpack "CUP_B_USPack_Black";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_personalAidKit";};
this addHeadgear "H_HelmetB_Light_tna_F";
this addGoggles "G_Bandanna_blk";
this addWeapon "hlc_rifle_CQBR";
this addPrimaryWeaponItem "hlc_muzzle_snds_AUG";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addPrimaryWeaponItem "CUP_acc_ANPEQ_2";
this addWeapon "CUP_hgun_Glock17_blk";
this addHandgunItem "CUP_acc_Glock17_Flashlight";
this linkItem "ItemMap";
this linkItem "ItemGPS";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "arcore_nightvision_Gen8";
