this forceAddUniform "U_O_CombatUniform_ocamo";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_EntrenchingTool";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "V_TacChestrig_cbr_F";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
for "_i" from 1 to 7 do {this addItemToVest "30Rnd_65x39_caseless_green";};
for "_i" from 1 to 3 do {this addItemToVest "30Rnd_65x39_caseless_green_mag_Tracer";};
this addBackpack "B_Carryall_khk";
for "_i" from 1 to 2 do {this addItemToBackpack "Titan_AT";};
this addItemToBackpack "Titan_AP";
this addHeadgear "H_HelmetO_ocamo";
this addWeapon "arifle_Katiba_F";
this addPrimaryWeaponItem "optic_Aco";
this addWeapon "launch_O_Titan_short_F";
this addWeapon "hgun_Pistol_heavy_01_F";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";