this forceAddUniform "U_B_CTRG_Soldier_F";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "V_PlateCarrier1_rgr_noflag_F";
for "_i" from 1 to 8 do {this addItemToVest "hlc_30rnd_556x45_T_AUG";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_FlareRed_M203";};
for "_i" from 1 to 5 do {this addItemToVest "CUP_1Rnd_Smoke_M203";};
this addItemToVest "30rnd_9x21_Yellow_Mag";
this addItemToVest "ACE_IR_Strobe_Item";
this addHeadgear "H_HelmetB_TI_tna_F";
this addWeapon "hlc_rifle_auga3_GL";
this addPrimaryWeaponItem "cup_optic_compm4";
this addWeapon "hgun_P07_khk_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this addGoggles "G_Balaclava_TI_G_tna_F";