this forceAddUniform "MNP_CombatUniform_DS_B";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "HandGrenade";};
for "_i" from 1 to 5 do {this addItemToUniform "ACE_CableTie";};
this addVest "MNP_Vest_DS_1";
for "_i" from 1 to 3 do {this addItemToVest "CUP_15Rnd_9x19_M9";};
for "_i" from 1 to 2 do {this addItemToVest "hlc_200rnd_556x45_M_SAW";};
this addBackpack "B_Kitbag_mcamo";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200rnd_556x45_M_SAW";};
this addHeadgear "CUP_H_USMC_MICH2000_DEF_ESS_WDL";
this addWeapon "hlc_m249_pip4";
this addPrimaryWeaponItem "CUP_optic_Eotech533Grey";
this addPrimaryWeaponItem "HLC_bipod_UTGShooters";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";