this forceAddUniform "MNP_CombatUniform_DS_A";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_CableTie";};
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
this addVest "MNP_Vest_DS_1";
for "_i" from 1 to 2 do {this addItemToVest "CUP_15Rnd_9x19_M9";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 5 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
for "_i" from 1 to 3 do {this addItemToVest "hlc_30rnd_556x45_TDim";};
this addBackpack "B_FieldPack_cbr";
for "_i" from 1 to 5 do {this addItemToBackpack "CUP_1Rnd_HE_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_HEDP_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_FlareWhite_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_Smoke_M203";};
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_SmokeRed_M203";};
for "_i" from 1 to 6 do {this addItemToBackpack "CUP_1Rnd_SmokeGreen_M203";};
for "_i" from 1 to 4 do {this addItemToBackpack "CUP_1Rnd_SmokeYellow_M203";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 4 do {this addItemToBackpack "Laserbatteries";};
this addHeadgear "CUP_H_USMC_LWH_NVGMOUNT_ESS_LR_WDL";
this addWeapon "hlc_rifle_m4m203";
this addPrimaryWeaponItem "optic_Holosight_blk_F";
this addWeapon "CUP_hgun_M9";
this addWeapon "Laserdesignator";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";