this forceAddUniform "MNP_CombatUniform_DS_B";
for "_i" from 1 to 4 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "SmokeShell";
this addItemToUniform "SmokeShellPurple";
this addVest "MNP_Vest_DS_2";
for "_i" from 1 to 3 do {this addItemToVest "CUP_15Rnd_9x19_M9";};
for "_i" from 1 to 5 do {this addItemToVest "hlc_30rnd_556x45_EPR";};
this addItemToVest "CUP_HandGrenade_M67";
this addBackpack "B_FieldPack_khk";
this addItemToBackpack "ToolKit";
this addHeadgear "usm_helmet_cvc";
this addWeapon "hlc_rifle_Colt727";
this addWeapon "CUP_hgun_M9";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";