this forceAddUniform "MNP_CombatUniform_Fin_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_RAV_IDF";
this addItemToVest "HandGrenade";
this addItemToVest "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_Red";};
this addBackpack "SP_Carryall_Green";
for "_i" from 1 to 3 do {this addItemToBackpack "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Red_M";};
this addHeadgear "MNP_Helmet_FIN_T";
this addWeapon "CUP_lmg_PKM";
this addWeapon "hgun_P07_F";
this addHandgunItem "16Rnd_9x21_Mag";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
