this forceAddUniform "MNP_CombatUniform_Fin_A";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CFP_RAV_IDF";
for "_i" from 1 to 6 do {this addItemToVest "hlc_30rnd_556x45_EPR_G36";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_30rnd_556x45_Tracers_G36";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_HandFlare_Red";};
this addItemToVest "HandGrenade";
this addHeadgear "MNP_Helmet_FIN_T";
this addWeapon "hlc_rifle_g36KTac";
this addPrimaryWeaponItem "CUP_optic_MicroT1_low";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addWeapon "hgun_P07_F";
this addHandgunItem "16Rnd_9x21_Mag";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
